apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: zabbix-monitoring
  creationTimestamp: null
  labels:
    io.kompose.service: zabbix-proxy-pvc
  name: zabbix-proxy-pvc
spec:
  storageClassName: nfs-csi-synologynas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
status: {}
