apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: kube-system
spec:
  plugin:
    crowdsec-bouncer:
      enabled: true
      crowdsecMode: stream
      crowdsecLapiScheme: https
      crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
      crowdsecLapiTLSCertificateBouncerFile: /certs/tls.crt
      crowdsecLapiTLSCertificateBouncerKeyFile: /certs/tls.key
      crowdsecLapiKey: ""
---
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: crowdsec-bouncer
#   namespace: kube-system
# spec:
#   plugin:
#     crowdsec-bouncer:
#       enabled: true
#       logLevel: INFO
#       updateIntervalSeconds: 30
#       crowdsecMode: stream
#       crowdsecLapiScheme: http
#       crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
#       crowdsecLapiKey: "${LAPI_BOUNCER_KEY}"
---
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: crowdsec-bouncer
#   namespace: default
# spec:
#   plugin:
#     crowdsec-bouncer:
#       enabled: true
#       crowdsecMode: appsec
#       crowdsecAppsecEnabled: true
#       crowdsecAppsecHost: crowdsec-appsec-service:7422
#       crowdsecLapiScheme: http
#       crowdsecLapiHost: crowdsec-service:8080
#       crowdsecLapiKey: "${LAPI_BOUNCER_KEY}"
