# MUST RUN THIS FIRST: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-pool-dev
  namespace: metallb-system
spec:
  addresses:
    - 192.168.86.225-192.168.86.226
  autoAssign: true
  avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
---
apiVersion: v1
kind: Service
metadata:
  name: metallb-metrics
  namespace: metallb-system
  labels:
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - port: 7472
      targetPort: 7472
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/name: metallb
# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: metallb-ingress
#   namespace: metallb-system
#   annotations:
#     kubernetes.io/ingress.class: traefik-external
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`metallb-metrics.local.timmybtech.com`)
#       kind: Rule
#       services:
#         - name: metallb-metrics
#           port: 7472
#   tls:
#     secretName: local-timmybtech-com-tls
