apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-usage-cost
  namespace: scripts
  labels:
    app: aws-usage-cost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-usage-cost
  template:
    metadata:
      labels:
        app: aws-usage-cost
    spec:
      containers:
        - name: aws-usage-cost
          image: timmyb824/aws-usage-cost:latest
          imagePullPolicy: Always
          env:
            - name: NTFY_TOPIC
              value: <path:secret/data/scripts#NTFY_TOPIC>
            - name: NTFY_ACCESS_TOKEN
              value: <path:secret/data/scripts#NTFY_ACCESS_TOKEN>
            - name: GOTIFY_HOST
              value: <path:secret/data/scripts#GOTIFY_HOST>
            - name: GOTIFY_TOKEN_ADHOC_SCRIPTS
              value: <path:secret/data/scripts#GOTIFY_TOKEN_ADHOC_SCRIPTS>
            - name: HEALTHCHECKS_URL_AWS_USAGE_COST
              value: <path:secret/data/scripts#HEALTHCHECKS_URL_AWS_USAGE_COST>
            - name: DISCORD_WEBHOOK_URL
              value: <path:secret/data/scripts#DISCORD_WEBHOOK_URL>
            - name: AWS_ACCESS_KEY_ID
              value: <path:secret/data/scripts#AWS_ACCESS_KEY_ID>
            - name: AWS_SECRET_ACCESS_KEY
              value: <path:secret/data/scripts#AWS_SECRET_ACCESS_KEY>
            - name: THRESHOLD
              value: "5"
            - name: INTERVAL_SCHEDULE
              value: "24 hours"
