---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-usage-cost
  namespace: scripts
spec:
  schedule: "0 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aws-usage-cost
              image: registry.local.timmybtech.com/aws-usage-cost:latest
              env:
                - name: N8N_WEBHOOK_URL
                  value: <path:secret/data/scripts#N8N_WEBHOOK_URL>
                - name: N8N_CREDENTIALS
                  value: <path:secret/data/scripts#N8N_CREDENTIALS>
                - name: AWS_ACCESS_KEY_ID
                  value: <path:secret/data/scripts#AWS_ACCESS_KEY_ID>
                - name: AWS_SECRET_ACCESS_KEY
                  value: <path:secret/data/scripts#AWS_SECRET_ACCESS_KEY>
                - name: HEALTHCHECKS_URL_AWS_USAGE_COST
                  value: <path:secret/data/scripts#HEALTHCHECKS_URL_AWS_USAGE_COST>
                - name: DISCORD_WEBHOOK_URL
                  value: <path:secret/data/scripts#DISCORD_WEBHOOK_URL>
                - name: THRESHOLD
                  value: "5.0"
          restartPolicy: OnFailure
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: aws-usage-cost
#   namespace: scripts
#   labels:
#     app: aws-usage-cost
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: aws-usage-cost
#   template:
#     metadata:
#       labels:
#         app: aws-usage-cost
#     spec:
#       containers:
#         - name: aws-usage-cost
#           image: timmyb824/aws-usage-cost:latest
#           imagePullPolicy: Always
#           env:
#             - name: N8N_WEBHOOK_URL
#               value: <path:secret/data/scripts#N8N_WEBHOOK_URL>
#             - name: N8N_CREDENTIALS
#               value: <path:secret/data/scripts#N8N_CREDENTIALS>
#             - name: HEALTHCHECKS_URL_AWS_USAGE_COST
#               value: <path:secret/data/scripts#HEALTHCHECKS_URL_AWS_USAGE_COST>
#             - name: DISCORD_WEBHOOK_URL
#               value: <path:secret/data/scripts#DISCORD_WEBHOOK_URL>
#             - name: AWS_ACCESS_KEY_ID
#               value: <path:secret/data/scripts#AWS_ACCESS_KEY_ID>
#             - name: AWS_SECRET_ACCESS_KEY
#               value: <path:secret/data/scripts#AWS_SECRET_ACCESS_KEY>
#             - name: THRESHOLD
#               value: "5"
