apiVersion: v1
kind: ConfigMap
metadata:
  name: oci-pem
  namespace: scripts
data:
  oci.pem: |
    <path:secret/data/scripts#OCI_PEM>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oci-config
  namespace: scripts
data:
  config: |
    <path:secret/data/scripts#OCI_CONFIG>
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: oci-usage-cost
  namespace: scripts
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: oci-usage-cost
              image: timmyb824/oci-usage-cost:latest
              env:
                - name: N8N_WEBHOOK_URL
                  value: <path:secret/data/scripts#N8N_WEBHOOK_URL>
                - name: N8N_CREDENTIALS
                  value: <path:secret/data/scripts#N8N_CREDENTIALS>
                - name: HEALTHCHECKS_URL_OCI_USAGE_COST
                  value: <path:secret/data/scripts#HEALTHCHECKS_URL_OCI_USAGE_COST>
                - name: DISCORD_WEBHOOK_URL
                  value: <path:secret/data/scripts#DISCORD_WEBHOOK_URL>
                - name: THRESHOLD
                  value: "5.0"
              volumeMounts:
                - name: oci-pem
                  mountPath: /scripts/oci.pem
                  subPath: oci.pem
                - name: oci-config
                  mountPath: /scripts/config
                  subPath: config
          volumes:
            - name: oci-pem
              configMap:
                name: oci-pem
            - name: oci-config
              configMap:
                name: oci-config
          restartPolicy: OnFailure
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: oci-usage-cost
#   namespace: scripts
#   labels:
#     app: oci-usage-cost
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: oci-usage-cost
#   template:
#     metadata:
#       labels:
#         app: oci-usage-cost
#     spec:
#       containers:
#         - name: oci-usage-cost
#           image: timmyb824/oci-usage-cost:latest
#           env:
#             - name: N8N_WEBHOOK_URL
#               value: <path:secret/data/scripts#N8N_WEBHOOK_URL>
#             - name: N8N_CREDENTIALS
#               value: <path:secret/data/scripts#N8N_CREDENTIALS>
#             - name: HEALTHCHECKS_URL_OCI_USAGE_COST
#               value: <path:secret/data/scripts#HEALTHCHECKS_URL_OCI_USAGE_COST>
#             - name: DISCORD_WEBHOOK_URL
#               value: <path:secret/data/scripts#DISCORD_WEBHOOK_URL>
#             - name: THRESHOLD
#               value: "5.0"
#           volumeMounts:
#             - name: oci-pem
#               mountPath: /scripts/oci.pem
#               subPath: oci.pem
#             - name: oci-config
#               mountPath: /scripts/config
#               subPath: config
#       volumes:
#         - name: oci-pem
#           configMap:
#             name: oci-pem
#         - name: oci-config
#           configMap:
#             name: oci-config
