apiVersion: v1
kind: Service
metadata:
  namespace: code-server
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: code-server
  name: code-server
spec:
  ports:
    - name: "8446"
      port: 8446
      targetPort: 8446
  selector:
    io.kompose.service: code-server
status:
  loadBalancer: {}
