apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: crowdsec-agent-metrics-ingress
  namespace: crowdsec
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`crowdsec-agent-metrics.local.timmybtech.com`)
      kind: Rule
      services:
        - name: crowdsec-agent-service
          port: 6060
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: crowdsec-lapi-metrics-ingress
  namespace: crowdsec
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`crowdsec-metrics.local.timmybtech.com`)
      kind: Rule
      services:
        - name: crowdsec-service
          port: 6060
  tls:
    secretName: local-timmybtech-com-tls
