repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--unsafe] # prevents loading the yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ["--fix=auto"]

  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.9 # Use latest tag on GitHub
    hooks:
      - id: ripsecrets

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.88.23
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail'
        language: system
        stages: ["pre-commit"]

  - repo: https://github.com/timmyb824/sops-file-encryption-check
    rev: latest
    hooks:
      - id: sops-encryption-check
#

# Example of local hook
# -   repo: local
#     hooks:
#     - id: empty file contents
#       name: empty file contents
#       entry: ./scripts/empty_file_contents.sh
#       language: script
#       files: app.json
