apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: grafana-pvc
spec:
  storageClassName: nfs-csi-synologynas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "20Gi"
status: {}
