apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: traefik
spec:
  plugin:
    crowdsec-bouncer:
      enabled: true
      crowdsecMode: none
      crowdsecLapiScheme: https
      crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
      # export key and use envsubst to insert at apply time
      # i.e. `envsubst < crowdsec-bouncer-middleware.yaml | kubectl apply -f -`
      crowdsecLapiKey: "$LAPI_BOUNCER_KEY"
      crowdsecLapiTLSInsecureVerify: true
