globalArguments:
  - --global.sendanonymoususage=false
  - --global.checknewversion=false
additionalArguments:
  - --serversTransport.insecureSkipVerify=true
  - --log.level=INFO
deployment:
  enabled: true
  replicas: 1
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []
ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    tls:
      enabled: true

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external-dev
    allowExternalNameServices: true
    allowCrossNamespace: true # FOR AUTHENTIK
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    loadBalancerIP: 192.168.86.225 # This should be an IP in the MetalLB range
  loadBalancerSourceRanges: []
  externalIPs: []
logs:
  access:
    enabled: true
    format: json
  general:
    format: json
