---
apiVersion: v1
kind: Namespace
metadata:
  name: notifiq
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notifiq-config
  namespace: notifiq
data:
  RABBITMQ_HOST: "rabbitmq.rabbitmq.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "<path:secret/data/argocd#RABBITMQ_USERNAME>"
  RABBITMQ_PASS: "<path:secret/data/argocd#RABBITMQ_PASSWORD>"
  RABBITMQ_QUEUE: "homelab.alerts"
  APPRISE_NTFY_URL: "<path:secret/data/argocd#NOTIFIQ_APPRISE_NTFY_URL>"
  APPRISE_DISCORD_URL: "<path:secret/data/argocd#NOTIFIQ_APPRISE_DISCORD_URL>?channel=alerts"
  APPRISE_EMAIL_URL: "<path:secret/data/argocd#NOTIFIQ_APPRISE_EMAIL_URL>"
  APPRISE_MATTERMOST_URL: "<path:secret/data/argocd#NOTIFIQ_APPRISE_MATTERMOST_URL>"
  APPRISE_GOTIFY_URL: "<path:secret/data/argocd#NOTIFIQ_APPRISE_GOTIFY_URL>"
  APPRISE_PUSHOVER_URL: "<path:secret/data/argocd#NOTIFIQ_APPRISE_PUSHOVER_URL>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifiq
  namespace: notifiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifiq
  template:
    metadata:
      labels:
        app: notifiq
        app.kubernetes.io/name: notifiq
    spec:
      containers:
        - name: notifiq
          image: registry.local.timmybtech.com/notifiq:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: notifiq-config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: notifiq
  namespace: notifiq
spec:
  type: ClusterIP
  selector:
    app: notifiq
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: notifiq-internal
  namespace: notifiq
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`notifiq.local.timmybtech.com`)
      kind: Rule
      services:
        - name: notifiq
          port: 8080
  tls:
    secretName: local-timmybtech-com-tls
