---
apiVersion: v1
kind: Namespace
metadata:
  name: umami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    io.kompose.service: umami
  name: umami
  namespace: umami
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: umami
  template:
    metadata:
      annotations:
        avp.kubernetes.io/path: "secret/data/umami"
      labels:
        io.kompose.service: umami
        app.kubernetes.io/name: umami
    spec:
      containers:
        - env:
            - name: APP_SECRET
              value: <path:secret/data/umami#APP_SECRET>
            - name: DATABASE_TYPE
              value: postgresql
            - name: DATABASE_URL
              value: <path:secret/data/umami#PG_URL>
          image: ghcr.io/umami-software/umami:postgresql-v2.13.2
          name: umami
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  namespace: umami
  labels:
    io.kompose.service: umami
  name: umami
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: umami
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: umami-internal
  namespace: umami
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`umami.local.timmybtech.com`)
      kind: Rule
      services:
        - name: umami
          port: 3000
      # middlewares:
      #   - name: crowdsec-bouncer
      #     namespace: traefik
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: umami-public
  namespace: umami
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`umami.timmybtech.com`)
      kind: Rule
      services:
        - name: umami
          port: 3000
  tls:
    secretName: timmybtech-com-tls
