globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"

deployment:
  enabled: true
  replicas: 3
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external # can name this anything
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: false
  file:
    enabled: true
    watch: true
    content: |
      tls:
          certificates:
            - certFile: /certs/tls.crt
              keyFile: /certs/tls.key
        stores:
            default:
              defaultCertificate:
                certFile: /certs/tls.crt
                keyFile: /certs/tls.key
        http:
            routers:
                wyl:
                    rule: Host(`wyl.local.timmybtech.com`)
                    service: wyl
                    entrypoints:
                        - websecure
                    tls:
                        certResolver: default
            services:
                wyl:
                    loadBalancer:
                        servers:
                            - url: http://192.168.86.202:8840
volumes:
  - name: local-timmybtech-com-tls
    mountPath: /certs
    type: secret

additionalVolumeMounts:
  - name: local-timmybtech-com-tls
    mountPath: /certs
    readOnly: true

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    loadBalancerIP: 192.168.86.224 # this should be an IP in the MetalLB range
  loadBalancerSourceRanges: []
  externalIPs: []
