---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-timmybtech-com
  namespace: traefik
spec:
  secretName: local-timmybtech-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.timmybtech.com"
  dnsNames:
  - "local.timmybtech.com"
  - "*.local.timmybtech.com"
