apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    avp.kubernetes.io/path: "secret/data/authentik"
spec:
  destination:
    namespace: authentik
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io
      targetRevision: 2024.12.0
      chart: authentik
      helm:
        releaseName: authentik
        values: |
          authentik:
              secret_key: <SECRET_KEY>
              # This sends anonymous usage-data, stack traces on errors and
              # performance data to sentry.io, and is fully opt-in
              error_reporting:
                enabled: false
              postgresql:
                host: <PG_HOST>
                name: "authentik"
                user: <PG_USER>
                password: <PG_PASSWORD>
                port: 5432
              email:
                host: "smtp.gmail.com"
                port: 587
                username: "<SMTP_USER>"
                password: "<SMTP_PASSWORD>"
                use_tls: false
                use_ssl: false
                timeout: 30
                from: "authentik@local.timmybtech.com"

          server:
            ingress:
              enabled: false

          postgresql:
            enabled: false

          redis:
              enabled: true

          metrics:
            enabled: true

    - repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
      path: "gitops/manifests/authentik"
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
