apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    avp.kubernetes.io/path: "secret/data/authentik"
spec:
  destination:
    namespace: authentik
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    targetRevision: 2024.12.1
    chart: authentik
    helm:
      releaseName: authentik
      values: |
        authentik:
            secret_key: <SECRET_KEY>
            # This sends anonymous usage-data, stack traces on errors and
            # performance data to sentry.io, and is fully opt-in
            error_reporting:
                enabled: false
            postgresql:
              host: <PG_HOST>
              name: "authentik"
              user: <PG_USER>
              password: <PG_PASSWORD>
              port: 5432
            email:
              host: "smtp.gmail.com"
              port: 587
              username: "<SMTP_USER>"
              password: "<SMTP_PASSWORD>"
              use_tls: false
              use_ssl: false
              timeout: 30
              from: "authentik@local.timmybtech.com"

        server:
          ingress:
            enabled: false

        postgresql:
          enabled: false

        redis:
            enabled: true

        metrics:
          enabled: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-ingress
  namespace: authentik
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`authentik.local.timmybtech.com`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
  tls:
    secretName: local-timmybtech-com-tls
---

---
apiVersion: v1
kind: Service
metadata:
  name: authentik-metrics
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/name: authentik
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-metrics-ingress
  namespace: authentik
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`authentik-metrics.local.timmybtech.com`)
      kind: Rule
      services:
        - name: authentik-metrics
          port: 9300
  tls:
    secretName: local-timmybtech-com-tls
