apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    avp.kubernetes.io/path: "secret/data/authentik"
spec:
  destination:
    namespace: authentik
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io
      targetRevision: 2024.12.0
      chart: authentik
      helm:
        releaseName: authentik
        values: |
          authentik:
            error_reporting:
              enabled: false
            env:
              - name: AUTHENTIK_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: authentik-secret
                    key: secret-key
              - name: AUTHENTIK_POSTGRESQL__HOST
                valueFrom:
                  secretKeyRef:
                    name: authentik-secret
                    key: pg-host
              - name: AUTHENTIK_POSTGRESQL__NAME
                value: "authentik"
              - name: AUTHENTIK_POSTGRESQL__USER
                valueFrom:
                  secretKeyRef:
                    name: authentik-secret
                    key: pg-user
              - name: AUTHENTIK_POSTGRESQL__PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: authentik-secret
                    key: pg-password
              - name: AUTHENTIK_POSTGRESQL__PORT
                value: "5432"
              - name: AUTHENTIK_EMAIL__HOST
                value: "smtp.gmail.com"
              - name: AUTHENTIK_EMAIL__PORT
                value: "587"
              - name: AUTHENTIK_EMAIL__USERNAME
                valueFrom:
                  secretKeyRef:
                    name: authentik-secret
                    key: smtp-user
              - name: AUTHENTIK_EMAIL__PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: authentik-secret
                    key: smtp-password
              - name: AUTHENTIK_EMAIL__USE_TLS
                value: "false"
              - name: AUTHENTIK_EMAIL__USE_SSL
                value: "false"
              - name: AUTHENTIK_EMAIL__TIMEOUT
                value: "30"
              - name: AUTHENTIK_EMAIL__FROM
                value: "authentik@local.timmybtech.com"

          server:
            ingress:
              enabled: false

          postgresql:
            enabled: false

          redis:
            enabled: true

          metrics:
            enabled: true

    - repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
      path: "gitops/manifests/authentik"
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
