apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  destination:
    namespace: authentik
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io
      targetRevision: 2025.12.2
      chart: authentik
      helm:
        releaseName: authentik
        values: |
          authentik:
              secret_key: <path:secret/data/authentik#SECRET_KEY>
              error_reporting:
                enabled: false
              postgresql:
                host: <path:secret/data/authentik#PG_HOST>
                name: "authentik_utf8"
                user: <path:secret/data/authentik#PG_USER>
                password: <path:secret/data/authentik#PG_PASSWORD>
                port: 5432
              redis:
                host: <path:secret/data/authentik#REDIS_HOST>
                password: <path:secret/data/authentik#REDIS_PASSWORD>
              email:
                host: "smtp.gmail.com"
                port: 587
                username: "<path:secret/data/authentik#SMTP_USER>"
                password: "<path:secret/data/authentik#SMTP_PASSWORD>"
                use_tls: false
                use_ssl: false
                timeout: 30
                from: "authentik@local.timmybtech.com"

          server:
            ingress:
              enabled: false
            resources:
              requests:
                cpu: "100m"
                memory: "512Mi"
              limits:
                cpu: "500m"
                memory: "1Gi"

          worker:
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "768Mi"

          postgresql:
            enabled: false

          redis:
              enabled: false

          metrics:
            enabled: true

    - repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
      path: "gitops/manifests/authentik"
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
