authentik:
  secret_key: <path:secret/data/authentik#SECRET_KEY>
  error_reporting:
    enabled: false
  postgresql:
    host: <path:secret/data/authentik#PG_HOST>
    name: "authentik"
    user: <path:secret/data/authentik#PG_USER>
    password: <path:secret/data/authentik#PG_PASSWORD>
    port: 5432
  email:
    host: "smtp.gmail.com"
    port: 587
    username: "<path:secret/data/authentik#SMTP_USER>"
    password: "<path:secret/data/authentik#SMTP_PASSWORD>"
    use_tls: false
    use_ssl: false
    timeout: 30
    from: "authentik@local.timmybtech.com"

server:
  ingress:
    enabled: false

postgresql:
  enabled: false

redis:
  enabled: true

metrics:
  enabled: true
