apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io
      targetRevision: 2024.12.0
      chart: authentik
      helm:
        releaseName: authentik
        parameters:
          - name: "authentik.secret_key"
            valueFrom:
              configMapKeyRef:
                name: authentik-config
                key: secret_key
          - name: "authentik.error_reporting.enabled"
            value: "false"
          - name: "authentik.postgresql.host"
            valueFrom:
              configMapKeyRef:
                name: authentik-config
                key: pg_host
          - name: "authentik.postgresql.name"
            value: "authentik"
          - name: "authentik.postgresql.user"
            valueFrom:
              configMapKeyRef:
                name: authentik-config
                key: pg_user
          - name: "authentik.postgresql.password"
            valueFrom:
              configMapKeyRef:
                name: authentik-config
                key: pg_password
          - name: "authentik.postgresql.port"
            value: "5432"
          - name: "authentik.email.host"
            value: "smtp.gmail.com"
          - name: "authentik.email.port"
            value: "587"
          - name: "authentik.email.username"
            valueFrom:
              configMapKeyRef:
                name: authentik-config
                key: smtp_user
          - name: "authentik.email.password"
            valueFrom:
              configMapKeyRef:
                name: authentik-config
                key: smtp_password
          - name: "authentik.email.use_tls"
            value: "false"
          - name: "authentik.email.use_ssl"
            value: "false"
          - name: "authentik.email.timeout"
            value: "30"
          - name: "authentik.email.from"
            value: "authentik@local.timmybtech.com"
          - name: "server.ingress.enabled"
            value: "false"
          - name: "postgresql.enabled"
            value: "false"
          - name: "redis.enabled"
            value: "true"
          - name: "metrics.enabled"
            value: "true"
    - repoURL: https://github.com/timmyb824/kubernetes-apps.git
      path: gitops/manifests/authentik
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
