apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: authentik
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io
      targetRevision: 2024.12.0
      chart: authentik
      helm:
        releaseName: authentik
        values: |
          authentik:
            # Tell Authentik to use our external secret
            existingSecret: authentik-secrets
            error_reporting:
              enabled: false
            email:
              host: "smtp.gmail.com"
              port: 587
              use_tls: false
              use_ssl: false
              timeout: 30
              from: "authentik@local.timmybtech.com"

            postgresql:
              name: "authentik"
              port: 5432

          server:
            ingress:
              enabled: false

          postgresql:
            enabled: false

          redis:
              enabled: true

          metrics:
            enabled: true

    - repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
      path: "gitops/manifests/authentik"
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
