apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: botkube
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    avp.kubernetes.io/path: "secret/data/botkube"
spec:
  destination:
    namespace: botkube
    server: "https://kubernetes.default.svc"
  project: default
  sources:
  - repoURL: https://charts.botkube.io
    targetRevision: 1.1.1
    chart: botkube
    helm:
      releaseName: botkube
      parameters:
      - name: "communications.default-group.discord.enabled"
        value: "true"
      - name: "communications.default-group.discord.botID"
        value: "<DISCORD_BOT_ID>"
      - name: "communications.default-group.discord.token"
        value: "<DISCORD_TOKEN>"
      - name: "communications.default-group.discord.channels.default.id"
        value: "<DISCORD_CHANNEL_ID>"
      - name: "executors.ai.botkube/doctor.enabled"
        value: "true"
      - name: "executors.ai.botkube/doctor.config.apiKey"
        value: "<OPENAI_API_KEY>"
      valueFiles:
      - $values/gitops/manifests/botkube/overrides.yaml
  - repoURL: 'https://github.com/timmyb824/kubernetes-apps.git'
    targetRevision: HEAD
    ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
