apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: botkube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    avp.kubernetes.io/path: "secret/data/botkube"
spec:
  destination:
    namespace: botkube
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://charts.botkube.io
    targetRevision: 1.14.0
    chart: botkube
    helm:
      releaseName: botkube
      valueFiles:
        - "gitops/manifests/botkube/values.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
