apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: botkube
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    avp.kubernetes.io/path: "secret/data/slack"
spec:
  destination:
    namespace: botkube
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://charts.botkube.io
    targetRevision: 0.18.0
    chart: botkube
    helm:
      releaseName: botkube
      parameters:
      - name: "communications.default-group.socketSlack.enabled"
        value: "true"
      - name: "communications.default-group.socketSlack.channels.default.name"
        value: "homelab"
      - name: "communications.default-group.socketSlack.appToken="
        value: "<SLACK_API_APP_TOKEN>"
      - name: "communications.default-group.socketSlack.botToken="
        value: "<SLACK_API_BOT_TOKEN>"
      - name: "settings.clusterName"
        value: "default"
      - name: "executors.kubectl-read-only.kubectl.enabled"
        value: "true"
      - name: "executors.helm.botkube/helm.enabled"
        value: "true"
        forceString: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
