apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-syncer
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    avp.kubernetes.io/path: "secret/data/botkube"
spec:
  destination:
    namespace: kubeops
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: oci://ghcr.io/appscode-charts/config-syncer
    targetRevision: v0.15.2
    chart: config-syncer
    helm:
      releaseName:
      values: |
        replicaCount: 1

        # License for the product.
        # Get a license by following the steps from [here](https://license-issuer.appscode.com/).
        # Example:
        # helm install appscode/panopticon \
        #   --set-file license=/path/to/license/file
        # or
        # helm install appscode/panopticon \
        #   --set license=<license file content>
        license: <path:secret/data/argocd#CONFIG_SYNCER_LICENSE>

        # oss or enterprise
        mode: oss

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
