apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  destination:
    namespace: crowdsec
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://crowdsecurity.github.io/helm-charts
    targetRevision: 0.16.0
    chart: crowdsec
    helm:
      releaseName: crowdsec
      values: |
        # for raw logs format: json or cri (docker|containerd)
        container_runtime: containerd
        agent:
          # Specify each pod whose logs you want to process
          acquisition:
            # The namespace where the pod is located
            - namespace: traefik
              # The pod name
              podName: traefik-*
              # as in crowdsec configuration, we need to specify the program name to find a matching parser
              program: traefik
          env:
            - name: COLLECTIONS
              value: "crowdsecurity/traefik"
        lapi:
          env:
            # To enroll the Security Engine to the console
            - name: ENROLL_KEY
              value: "<path:secret/data/argocd#CROWDSEC_ENROLL_KEY_K8S>"
            - name: ENROLL_INSTANCE_NAME
              value: "k8s-cluster"
            - name: ENROLL_TAGS
              value: "k8s linux test"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
