apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docmost
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
    targetRevision: HEAD
    path: gitops/manifests/docmost
  destination:
    server: "https://kubernetes.default.svc"
    namespace: docmost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
