apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  destination:
    namespace: external-secrets
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      targetRevision: 0.15.1
      chart: external-secrets
      helm:
        releaseName: external-secrets
      values: |
        # -- If set, install and upgrade CRDs through helm chart.
        installCRDs: true

    - repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
      path: "gitops/manifests/external-secrets"
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
