apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-backup-tool
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana-backup-tool
    server: "https://kubernetes.default.svc"
  source:
    path: kubernetes/manifests/argocd/k8s-apps/grafana-backup-tool
    repoURL: "https://gitea.local.timmybtech.com/tbryant/homelab-onedrive.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
