apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heimdall
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: heimdall
    server: "https://kubernetes.default.svc"
  source:
    path: gitops/manifests/heimdall
    repoURL: "https://gitea.local.timmybtech.com/tbryant/kubernetes-apps.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
