apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous=true
spec:
  destination:
    namespace: immich
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://immich-app.github.io/immich-charts
      targetRevision: 0.10.3
      chart: immich
      helm:
        releaseName: immich
        values: |
          ## This chart relies on the common library chart from bjw-s
          ## You can find it at https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
          ## Refer there for more detail about the supported values

          # These entries are shared between all the Immich components

          env:
            DB_HOSTNAME:
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: DB_HOSTNAME
            DB_USERNAME:
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: DB_USERNAME
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: DB_PASSWORD
            DB_DATABASE_NAME:
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: DB_DATABASE_NAME
            DB_VECTOR_EXTENSION: "pgvector"
            REDIS_HOSTNAME:
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: REDIS_HOSTNAME
            REDIS_PORT:
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: REDIS_PORT
            REDIS_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: REDIS_PASSWORD
            IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'

          postgresql:
            enabled: false

          image:
            tag: v1.143.0

          immich:
            metrics:
              # Enabling this will create the service monitors needed to monitor immich with the prometheus operator
              enabled: true
            persistence:
              # Main data store for all photos shared between different components.
              library:
                existingClaim: immich-library-pvc
            # configuration is immich-config.json converted to yaml
            # ref: https://immich.app/docs/install/config-file/
            #
            configuration: {}
              # trash:
              #   enabled: false
              #   days: 30
              # storageTemplate:
              #   enabled: true
              #   template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"

          # Dependencies

          postgresql:
            enabled: false

          redis:
            enabled: false
            architecture: standalone
            auth:
              enabled: false

          # Immich components

          server:
            enabled: true
            image:
              repository: ghcr.io/immich-app/immich-server
              pullPolicy: IfNotPresent
            ingress:
              main:
                enabled: false
                annotations:
                  # proxy-body-size is set to 0 to remove the body limit on file uploads
                  nginx.ingress.kubernetes.io/proxy-body-size: "0"
                hosts:
                  - host: immich.local
                    paths:
                      - path: "/"
                tls: []

          machine-learning:
            enabled: true
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              pullPolicy: IfNotPresent
            env:
              TRANSFORMERS_CACHE: /cache
              HF_XET_CACHE: /cache/huggingface-xet
              MPLCONFIGDIR: /cache/matplotlib-config
            persistence:
              cache:
                enabled: true
                size: 10Gi
                # Optional: Set this to persistentVolumeClaim to avoid downloading the ML models every start.
                type: persistentVolumeClaim
                accessMode: ReadWriteMany
                storageClass: nfs-csi-synologynas

    - repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
      path: "gitops/manifests/immich"
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
