apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joplin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
    targetRevision: HEAD
    path: gitops/manifests/joplin
  destination:
    server: "https://kubernetes.default.svc"
    namespace: joplin
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
