apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  destination:
    namespace: metallb-system
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      targetRevision: 0.14.9
      chart: metallb
      helm:
        releaseName: metallb
    - repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
      path: "gitops/manifests/metallb"
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
