apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  destination:
    namespace: metallb-system
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.9
    chart: metallb
    helm:
      releaseName: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
