apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  destination:
    namespace: open-webui
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://open-webui.github.io/helm-charts
      targetRevision: 14.8.0
      chart: open-webui
      helm:
        releaseName: open-webui
        values: |
          namespaceOverride: "open-webui"
          replicaCount: 1
          ollama:
            enabled: false
          pipelines:
            enabled: false
          openaiBaseApiUrls:
            - "https://api.openai.com/v1"
            - "https://litellm.timmybtech.com/v1"
            - "http://hermes.homelab.lan:8642/v1"
          openaiApiKeys:
            # - "<path:secret/data/argocd#OPENUI_PIPELINE_KEY>" # enabled when pipelines are enabled
            - "<path:secret/data/argocd#OPENAI_PROJECT_KEY>"
            - "<path:secret/data/argocd#OPENUI_LITELLM_KEY>"
            - "<path:secret/data/argocd#OPENUI_HERMES_API_KEY>"
          websocket:
            enabled: true
            manager: redis
            url: "<path:secret/data/database#REDIS_CONN_STRING>/5"
            redis:
              enabled: false
          persistence:
            enabled: true
            provider: s3
            s3:
              accessKey: "<path:secret/data/argocd#OPENUI_S3_ACCESS_KEY>"
              secretKey: "<path:secret/data/argocd#OPENUI_S3_SECRET_KEY>"
              endpointUrl: "https://rustfs-endpoint.local.timmybtech.com"
              region: "us-east-1"
              bucket: "open-webui"
          databaseUrl: "<path:secret/data/database#PGQL_CONN_STRING>/openwebui"
          # sso:
          #   enabled: false
          #   enableSignup: false
          # oidc:
          #   enabled: true
          #   clientId: "<path:secret/data/argocd#OPENUI_AUTHENTIK_CLIENT_ID>"
          #   clientSecret: "<path:secret/data/argocd#OPENUI_AUTHENTIK_CLIENT_SECRET>"
          #   providerUrl: "<path:secret/data/argocd#OPENUI_AUTHENTIK_PROVIDER_URL>"
          #   providerName: "Authentik"
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

    - repoURL: "https://github.com/timmyb824/homelab-kubernetes-apps.git"
      path: "gitops/manifests/open-webui"
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
