apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: planka
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: planka
    server: "https://kubernetes.default.svc"
  source:
    path: gitops/manifests/planka
    repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
