apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: registry
    server: "https://kubernetes.default.svc"
  source:
    path: gitops/manifests/registry-server
    repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
