apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous=true
spec:
  destination:
    namespace: rustfs
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://charts.rustfs.com
      targetRevision: 0.0.83
      chart: rustfs
      helm:
        releaseName: rustfs
        values: |
          replicaCount: 1

          image:
            rustfs:
              repository: rustfs/rustfs
              pullPolicy: IfNotPresent
              tag: ""

          mode:
            standalone:
              enabled: true
            distributed:
              enabled: false

          secret:
            existingSecret: ""
            rustfs:
              access_key: rustfsadmin
              secret_key: rustfsadmin

          config:
            rustfs:
              volumes: ""
              address: ":9000"
              console_enable: "true"
              console_address: ":9001"
              log_level: "info"
              region: "us-east-1"
              obs_log_directory: "/logs"
              obs_environment: "development"
              domains: ""
              log_rotation:
                size: 100
                time: hour
                keep_files: 30

          podAnnotations:
            app.kubernetes.io/name: rustfs

          podLabels: {}

          commonLabels: {}

          podSecurityContext:
            fsGroup: 10001
            runAsUser: 10001
            runAsGroup: 10001

          containerSecurityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true

          ingress:
            enabled: true
            className: "traefik-external"
            traefikAnnotations:
              traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
              traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"
              traefik.ingress.kubernetes.io/service.sticky.cookie.name: rustfs
              traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: none
              traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
            customAnnotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
            hosts:
              - host: rustfs.local.timmybtech.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              enabled: true
              certManager:
                enabled: false
              secretName: local-timmybtech-com-tls

          gatewayApi:
            enabled: false

          mtls:
            enabled: false

          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

          livenessProbe:
            httpGet:
              path: /health
              port: endpoint
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: endpoint
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3

          storageclass:
            name: nfs-csi-synologynas
            dataStorageSize: 32Gi
            logStorageSize: 8Gi

    - repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
      path: "gitops/manifests/rustfs"
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
