apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scraperr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  destination:
    namespace: scraperr
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://jaypyles.github.io/helm/charts/scraperr
      targetRevision: 1.1.4
      chart: scraperr
      helm:
        releaseName: scraperr
        values: |
          scraperr:
            image:
              repository: jpyles0524/scraperr
              tag: latest
              pullPolicy: IfNotPresent
            containerCommand: ["npm", "run","start"]
            containerPort: 3000
            serviceType: NodePort
            ports:
              - port: 80
                targetPort: 3000
                nodePort: 32300
                protocol: TCP
            env:
              - name: NEXT_PUBLIC_API_URL
                value: "http://scraperr-api:8000"
              - name: SERVER_URL
                value: "http://scraperr-api:8000"

          scraperrApi:
            image:
              repository: jpyles0524/scraperr_api
              tag: latest
              pullPolicy: IfNotPresent
            containerPort: 8000
            serviceType: ClusterIP
            ports:
              - port: 8000
                targetPort: 8000
                protocol: TCP
            env:
              - name: LOG_LEVEL
                value: "INFO"
            volumeMounts:
              - name: data
                mountPath: /project/app/data
              - name: media
                mountPath: /project/app/media
            volumes:
              - name: data
                hostPath:
                  path: /data/scraperr/data
                  type: DirectoryOrCreate
              - name: media
                hostPath:
                  path: /data/scraperr/media
          replicaCount: 1

    - repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
      path: "gitops/manifests/scraperr"
      targetRevision: HEAD

  patches:
    - target:
        kind: Deployment
        name: scraperr
        namespace: scraperr
      patch: |-
        - op: add
          path: /spec/template/spec/containers/0/resources
          value:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
    - target:
        kind: Deployment
        name: scraperr-api
        namespace: scraperr
      patch: |-
        - op: add
          path: /spec/template/spec/containers/0/resources
          value:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
