apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shlink
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: shlink
    server: "https://kubernetes.default.svc"
  source:
    path: gitops/manifests/shlink-web
    repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=false # created during shlink install
