apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: silverbullet
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: silverbullet
    server: "https://kubernetes.default.svc"
  source:
    path: gitops/manifests/silverbullet
    repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
