apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    avp.kubernetes.io/path: "secret/data/tailscale"
spec:
  destination:
    namespace: tailscale
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      targetRevision: 1.68.1
      chart: tailscale-operator
      helm:
        releaseName: tailscale-operator
        parameters:
          - name: oauth.clientId
            value: <0AUTH_CLIENT_ID_K8S>
          - name: oauth.clientSecret
            value: <0AUTH_CLIENT_SECRET_K8S>

    - repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
      path: "gitops/manifests/tailscale"
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
