apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    avp.kubernetes.io/path: "secret/data/tailscale"
spec:
  destination:
    namespace: tailscale
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      targetRevision: 1.96.5
      chart: tailscale-operator
      helm:
        releaseName: tailscale-operator
        values: |
          oauth:
            clientId: <0AUTH_CLIENT_ID_K8S>
            clientSecret: <0AUTH_CLIENT_SECRET_K8S>
          operatorConfig:
            resources:
              requests:
                cpu: 10m
                memory: 175Mi
              limits:
                cpu: 100m
                memory: 250Mi
    - repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
      path: "gitops/manifests/tailscale"
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
