apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zincobserve
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: zincobserve
    server: "https://kubernetes.default.svc"
  source:
    path: gitops/manifests/zincobserve
    repoURL: "https://gitea.local.timmybtech.com/tbryant/kubernetes-apps.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

