apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.86.220-192.168.86.224
  autoAssign: true
  avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
---
apiVersion: v1
kind: Service
metadata:
  name: metallb-metrics
  namespace: metallb-system
  labels:
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - port: 7472
      targetPort: 7472
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/name: metallb
