---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: windmill-internal
  namespace: windmill
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`windmill.local.timmybtech.com`)
      kind: Rule
      services:
        - name: windmill-app
          port: 8000
  tls:
    secretName: local-timmybtech-com-tls
# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: windmill-public
#   namespace: windmill
#   annotations:
#     kubernetes.io/ingress.class: traefik-external
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`windmill.timmybtech.com`)
#       kind: Rule
#       services:
#         - name: windmill-server
#           port: 80
#   tls:
#     secretName: timmybtech-com-tls
