---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token
  namespace: cert-manager
type: Opaque
stringData:
  cloudflare-token: $CF_TOKEN # NOT base64 encoded

# Make sure you are generating an API token and not a global API key https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens
# # Token Permissions:
# # Zone - DNS - Edit
# # Zone - Zone - Read
# # Zone Resources:
# # Include - All Zones
