---
# FOR REFERENCE ONLY
# Installation was handled with helm:
# helm install nfs-synologynas nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
# --set nfs.server=192.168.86.44 --set nfs.path=/volume1/kubernetes_dev --set storageClass.name=nfs-csi-synologynas \
# --set storageClass.defaultClass=true`
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-synologynas
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io:
parameters:
  server: 192.168.86.44
  share: /volume1/kubernetes_dev
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.0
