apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations: {}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/benphelps/homepage:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: homepage-config
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir:
            {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingress
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/description: Dynamically Detected Homepage
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Cluster Management
    gethomepage.dev/icon: homepage.png
    gethomepage.dev/name: Homepage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homepage.local.timmybtech.com`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    avp.kubernetes.io/path: "secret/data/homepage"
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Bryant Homelab
    headerStyle: boxed
  bookmarks.yaml: |
    - CICD:
        - Netlify:
            - abbr: NL
              href: https://app.netlify.com/
        - Renovate (GitHub App):
            - abbr: RG
              href: https://developer.mend.io/
        - Terraform Cloud:
            - abbr: TC
              href: https://app.terraform.io/app/Bryant-homelab/workspaces
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
    - Observability:
        - Grafana Cloud:
            - abbr: GC
              href: https://grafana.com/auth/sign-in/?plcmt=top-nav&cta=myaccount
        - Netdata Cloud:
            - abbr: NC
              href: https://app.netdata.cloud/
    - Networking:
        - Cloudflare:
            - abbr: CF
              href: https://dash.cloudflare.com/
        - Ngrok:
            - abbr: NG
              href: https://dashboard.ngrok.com/
  services.yaml: |
    - Automation:
        - Ansible Semaphore:
            icon: ansible.png
            href: https://semaphore.timmybtech.com/auth/login
            description: Open-source web UI for Ansible
        - ChangeDetectionIO:
            icon: changedetection-io.png
            href: https://changedetection.local.timmybtech.com/
            description: ChangeDetection.io is a free service to monitor changes to HTML pages
            namespace: changedetection
            widget:
                type: changedetectionio
                url: https://changedetection.local.timmybtech.com
                key: <CHANGEDTECTIONIO_API_KEY>
        - Home Assistant:
            icon: home-assistant.png
            href: https://hass.timmybtech.com/
            description: Open-source home automation platform

    - CICD:
        - ArgoCD:
            icon: argocd.png
            href: https://argocd.local.timmybtech.com/
            description: Continuous delivery tool for Kubernetes
            namespace: argocd
            app: argocd-server
        - Jenkins:
            icon: jenkins.png
            href: https://jenkins.local.timmybtech.com/
            description: Open-source automation server
            namespace: jenkins
            app: jenkins-server

    - Networking:
        - Adguard Home:
            icon: adguard-home.png
            href: https://adguard.timmybtech.com/
            description: Network-wide software for blocking ads & local DNS
            widget:
                type: adguard
                url: http://pihole2.local.lan
                username: <ADGUARD_USER>
                password: <ADGUARD_PASSWORD>
        - Adguard Home Replica:
            icon: adguard-home.png
            href: https://adguard2.timmybtech.com/
            description: Network-wide software for blocking ads & local DNS
            widget:
                type: adguard
                url: http://rasberrypi.local.lan
                username: <ADGUARD_USER>
                password: <ADGUARD_PASSWORD>
        - Adguard Home Sync:
            icon: adguard-home.png
            href: http://192.168.86.174:8080/
            description: Syncs Adguard Home settings between instances
        - Speedtest-tracker:
            icon: speedtest-tracker.png
            href: https://speedtest.timmybtech.com/
            description: This program runs a speedtest check and graphs the results
            widget:
                type: speedtest
                url: http://vm304.local.lan:8083
        - Traefik-docker:
            icon: traefik.png
            href: https://traefik.timmybtech.com/
            description: Open-source reverse proxy and load balancer
            widget:
              type: traefik
              url: http://vm304.local.lan:8080
        - Traefik-k8s:
            icon: traefik.png
            href: https://traefik.local.timmybtech.com/
            description: Open-source reverse proxy and load balancer
            widget:
              type: traefik
              url: https://traefik.local.timmybtech.com
              username: <TRAEFIK_USER>
              password: <TRAEFIK_PASSWORD>
        - Tailscale:
            icon: tailscale.png
            href: https://login.tailscale.com/
            description: Tailscale makes it easy to create a secure network between your devices
        - WatchYourLAN:
            icon: homepage.png
            href: https://wyl.timmybtech.com/
            description: WatchYourLAN is a simple network monitoring tool

    - Observability:
        - AlertManager:
            icon: prometheus.png
            href: https://alertmanager.local.timmybtech.com/
            description: Prometheus Alertmanager
        - Karma:
            icon: prometheus.png
            href: https://karma.timmybtech.com/
            description: Alertmanager UI
        - Prometheus:
            icon: prometheus.png
            href: https://prometheus.local.timmybtech.com/
            description: Open-source monitoring system
            widget:
                type: prometheus
                url: https://prometheus.local.timmybtech.com
        - SNMP Exporter:
            icon: prometheus.png
            href: http://pihole2.local.lan:9116/
            description: SNMP Exporter
        - Grafana:
            icon: grafana.png
            href: https://grafana.local.timmybtech.com/
            description: Open-source analytics & monitoring solution
            namespace: monitoring
            app: grafana
            widget:
                type: grafana
                url: https://grafana.local.timmybtech.com
                username: <GRAFANA_USER>
                password: <GRAFANA_PASSWORD>
        - Healthchecks:
            icon: healthchecks.png
            href: https://healthchecks.timmybtech.com/
            description: Cron-job monitoring
        - Uptime Kuma:
            icon: uptime-kuma.png
            href: https://uptimekuma.timmybtech.com/
            description: Uptime monitoring
            widget:
                type: uptimekuma
                url: http://pihole2.local.lan:3001
                slug: homelab
        - Zabbix:
            icon: zabbix.png
            href: https://zabbix.timmybtech.com/
            description: Open-source monitoring software

    - Productivity:
        - ArchiveBox:
            icon: archivebox.png
            href: https://archivebox.timmybtech.com/
            description: Open-source self-hosted web archive
        - Firefly-iii:
            icon: firefly.png
            href: https://firefly.local.timmybtech.com/
            description: Open-source personal finance manager
            namespace: firefly-iii
            app: firefly-iii
        - Firefly-iii Importer:
            icon: firefly.png
            href: https://firefly-importer.local.timmybtech.com/
            description: Firefly-iii Importer
            namespace: firefly-iii
            app: importer
        - Gitea:
            icon: gitea.png
            href: "https://gitea.local.timmybtech.com/"
            description: self-hosted git service
            namespace: default
            app: gitea
        - Homebox:
            icon: homebox.png
            href: https://homebox.timmybtech.com/
            description: Track, Organize, and Manage your Things.

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    # - search:
    #     provider: custom
    #     url: https://whoogle.local.timmybtech.com/
    #     target: _blank
    - weatherapi:
        latitude: 41.8978
        longitude: -70.9090
        units: imperial
        apiKey: <WEATHERAPI_API_KEY>
        cache: 15
  docker.yaml: ""
