apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.containo.us
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
      - apiextensions.k8s.io
    resources:
      - nodes
      - pods
      - customresourcedefinitions/status
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations: {}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:v1.2.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: homepage-config
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-internal
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/description: Dynamically Detected Homepage
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Cluster Management
    gethomepage.dev/icon: homepage.png
    gethomepage.dev/name: Homepage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homepage.local.timmybtech.com`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: default
  annotations:
    gethomepage.dev/description: Dynamically Detected Homepage
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Cluster Management
    gethomepage.dev/icon: homepage.png
    gethomepage.dev/name: Homepage
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: homepage
      port:
        number: 3000
  tls:
    - hosts:
        - homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    avp.kubernetes.io/path: "secret/data/homepage"
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Bryant Homelab
    headerStyle: boxed
    cardBlur: sm
    layout:
      Kubernetes:
        icon: mdi-sail-boat
        style: row
        columns: 3
      Kubernetes hidden:
        header: false
        style: row
        columns: 3
      DNS:
        icon: mdi-dns
        style: row
        columns: 2
      Proxmox:
        icon: mdi-server
        style: row
        columns: 2
      Storage:
        icon: mdi-database-check
        style: row
        columns: 2
      VM/LXC:
        icon: mdi-server
        style: row
        columns: 2
      VM/LXC hidden:
        header: false
        style: row
        columns: 3
  bookmarks.yaml: |
    - CICD:
        - Netlify:
            - abbr: NL
              href: https://app.netlify.com/
        - Renovate (GitHub App):
            - abbr: RG
              href: https://developer.mend.io/
        - Terraform Cloud:
            - abbr: TC
              href: https://app.terraform.io/app/Bryant-homelab/workspaces
    - Cloud:
        - Oracle Cloud:
            - abbr: OC
              href: https://cloud.oracle.com/
    - Observability:
        - Grafana Cloud:
            - abbr: GC
              href: https://grafana.com/auth/sign-in/?plcmt=top-nav&cta=myaccount
        - Netdata Cloud:
            - abbr: NC
              href: https://app.netdata.cloud/
        - Yandex Metrica:
            - abbr: YM
              href: https://metrica.yandex.com/
    - Networking:
        - Cloudflare:
            - abbr: CF
              href: https://dash.cloudflare.com/
        - Tailscale:
            - abbr: TS
              href: https://login.tailscale.com/
        - Ngrok:
            - abbr: NG
              href: https://dashboard.ngrok.com/
    - Storage:
        - Synology Account:
            - abbr: SYA
              href: https://account.synology.com/en-us/overview?en-us=
    - Tooling:
        - Web Check:
            - abbr: WCK
              href: https://web-check.xyz/
        - Crowdsec:
            - abbr: CS
              href: https://app.crowdsec.net/
  services.yaml: |
    - Kubernetes:
        - Grafana:
            icon: grafana.png
            href: https://grafana.timmybtech.com/
            namespace: grafana
            app: grafana
            widget:
                type: grafana
                url: https://grafana.local.timmybtech.com
                username: <GRAFANA_USER>
                password: <GRAFANA_PASSWORD>
        - Authentik:
            icon: authentik.png
            href: https://authentik.local.timmybtech.com/
            namespace: authentik
            app: authentik
            widget:
              type: authentik
              url: https://authentik.local.timmybtech.com
              key: <AUTHENTIK_TOKEN>
        - Traefik-k8s:
            icon: traefik.png
            href: https://traefik.local.timmybtech.com/
            namespace: traefik
            app: traefik
            widget:
              type: traefik
              url: https://traefik.local.timmybtech.com
              username: <TRAEFIK_USER>
              password: <TRAEFIK_PASSWORD>
        - ArgoCD:
            icon: argo-cd.png
            href: https://argocd.local.timmybtech.com/
            namespace: argocd
            app: argocd-server
            widget:
              type: argocd
              url: https://argocd.local.timmybtech.com
              key: <ARGOCD_KEY>
        - Immich:
            icon: immich.png
            href: https://immich.local.timmybtech.com/
            namespace: immich
            app: server
            widget:
              type: immich
              url: https://immich.local.timmybtech.com
              key: <IMMICH_KEY>
              version: 2
        - Homebox:
            icon: homebox.png
            href: https://homebox.local.timmybtech.com/
            namespace: homebox
            app: homebox
            widget:
              type: homebox
              url: https://homebox.local.timmybtech.com
              username: <HOMEBOX_USER>
              password: <HOMEBOX_PASSWORD>
              fields: ["items", "locations", "totalValue"]
    - Kubernetes hidden:
        - Docmost:
            icon: kubernetes.png
            href: https://docmost.timmybtech.com/
            namespace: docmost
            app: docmost
        - Glance:
            icon: glance.png
            href: https://glance.local.timmybtech.com/
            namespace: glance
            app: glance
        - Hoarder:
            icon: hoarder.png
            href: https://hoarder.timmybtech.com/
            namespace: hoarder
            app: hoarder
        - InfluxDB:
            icon: influxdb.png
            href: https://influxdb.local.timmybtech.com/
            namespace: influxdb
            app: influxdb
        - Kube-State-Metrics:
            icon: kubernetes.png
            href: https://kube-state-metrics.local.timmybtech.com/
            namespace: kube-system
            app: kube-state-metrics
        - MinIO:
            icon: minio.png
            href: https://minio-ui.local.timmybtech.com/
            namespace: minio
            app: minio
        - Ntfy:
            icon: ntfy.png
            href: https://ntfy.timmybtech.com/
            namespace: ntfy
            app: ntfy
        - n8n:
            icon: n8n.png
            href: https://n8n.local.timmybtech.com/
            namespace: n8n
            app: n8n
        - Paperless-ngx:
            icon: paperless.png
            href: https://paperless.local.timmybtech.com/
            namespace: paperless-ngx
            app: paperless-ngx
        - Planka:
            icon: planka.png
            href: https://planka.local.timmybtech.com/
            namespace: planka
            app: planka
        - Portainer (k8s):
            icon: portainer.png
            href: https://portainer.local.timmybtech.com/
            namespace: portainer
            app: portainer
        - Registry:
            icon: docker.png
            href: https://registry-ui.local.timmybtech.com/
            namespace: registry
            app: registry-ui
        - Umami:
            icon: umami.png
            href: https://umami.timmybtech.com/
            namespace: umami
            app: umami
        - Vault:
            icon: vault.png
            href: https://vault.local.timmybtech.com/
            namespace: vault
            app: vault
        - Wallos:
            icon: wallos.png
            href: https://wallos.local.timmybtech.com/
            namespace: wallos
            app: wallos
        - SearXNG:
            icon: searxng.png
            href: https://searxng.local.timmybtech.com/
            namespace: searxng
            app: searxng
    - DNS:
        - Adguard Home:
            icon: adguard-home.png
            href: https://adguard.local.timmybtech.com/
            ping: http://192.168.86.214
            widget:
                type: adguard
                url: http://192.168.86.214
                username: <ADGUARD_USER>
                password: <ADGUARD_PASSWORD>
        - Adguard Home Secondary:
            icon: adguard-home.png
            href: https://adguard-secondary.local.timmybtech.com/
            ping: http://192.168.86.174
            widget:
                type: adguard
                url: http://192.168.86.174
                username: <ADGUARD_USER>
                password: <ADGUARD_PASSWORD>

    - Storage:
        - Synology:
            icon: synology.png
            href: https://nas.local.timmybtech.com/
            ping: http://192.168.86.44:5000/
            widget:
                type: diskstation
                url: http://192.168.86.44:5000/
                username: <SYNOLOGY_USER>
                password: <SYNOLOGY_PASSWORD>
        - Synology Download:
            icon: synology.png
            href: https://nas.local.timmybtech.com/
            ping: http://192.168.86.44:5000/
            widget:
                type: downloadstation
                url: http://192.168.86.44:5000/
                username: <SYNOLOGY_USER>
                password: <SYNOLOGY_PASSWORD>

    - Proxmox:
        - Proxmox2:
            icon: proxmox.png
            href: https://pve.local.timmybtech.com/
            ping: https://192.168.86.160:8006
        - Proxmox 3:
            icon: proxmox.png
            href: https://192.168.86.199:8006
            ping: https://192.168.86.199:8006

    - VM/LXC:
        - Speedtest-tracker:
            icon: speedtest-tracker.png
            href: https://speedtest.local.timmybtech.com/
            ping: http://192.168.86.143:8083
            widget:
                type: speedtest
                url: http://192.168.86.143:8083
        - Prometheus:
            icon: prometheus.png
            href: http://prometheus.local.timmybtech.com/
            ping: http://prometheus.homelab.lan:9090
            widget:
                type: prometheus
                url: http://prometheus.homelab.lan:9090
        - Uptime Kuma:
            icon: uptime-kuma.png
            href: https://uptime-kuma.local.timmybtech.com/
            ping: http://homelab-oci03.tailebee.ts.net:3001
            widget:
                type: uptimekuma
                url: http://homelab-oci03.tailebee.ts.net:3001
                slug: bryant-homelab
        - Netalertx:
            icon: netalertx.png
            href: https://netalertx.local.timmybtech.com/
            ping: http://192.168.86.44:20211
            widget:
                type: netalertx
                url: http://192.168.86.44:20211

    - VM/LXC hidden:
        - SNMP Exporter:
            icon: prometheus.png
            href: http://192.168.86.174:9116/
            ping: http://192.168.86.174:9116/
        - Adguard Sync:
            icon: adguard-home.png
            href: http://pihole2.homelab.lan:8080/
            ping: http://pihole2.homelab.lan:8080
        - ActualBudget:
            icon: actual-budget.png
            href: https://budget.local.timmybtech.com/
            ping: http://192.168.86.203:5006
        - Dozzle:
            icon: dozzle.png
            href: https://dozzle.local.timmybtech.com/
            ping: http://192.168.86.174:9999
        - Healthchecks:
            icon: healthchecks.png
            href: https://healthchecks.local.timmybtech.com/
            ping: http://192.168.86.143:8000
        - Home Assistant:
            icon: home-assistant.png
            href: https://homeassistant.local.timmybtech.com/
            ping: http://192.168.86.147:8123
        - IT-Tools:
            icon: it-tools.png
            href: https://it-tools.local.timmybtech.com/
            ping: http://192.168.86.143:5884
        - Loki:
            icon: loki.png
            href: https://loki.local.timmybtech.com/
            ping: http://192.168.86.146:3100/loki/api/v1/status/buildinfo
        - Maybe:
            icon: maybe.png
            href: https://maybe.local.timmybtech.com/
            ping: http://192.168.86.174:3003
        - PGweb :
            icon: postgres.png
            href: https://pgweb.local.timmybtech.com/
            ping: http://192.168.86.143:8081
        - Semaphore:
            icon: ansible.png
            href: https://semaphore.local.timmybtech.com/
            ping: http://192.168.86.143:3005
        - Your-Spotify:
            icon: spotify.png
            href: http://192.168.86.53:3000/
            ping: http://192.168.86.53:3000
        - WatchYourLAN:
            icon: homepage.png
            href: https://watchyourlan.local.timmybtech.com/
            ping: http://192.168.86.217:8840
  widgets.yaml: |
    - weatherapi:
        latitude: 41.8978
        longitude: -70.9090
        units: imperial
        apiKey: <WEATHERAPI_API_KEY>
        cache: 15
    - search:
        provider: custom
        url: https://searxng.local.timmybtech.com/search?q=
        target: _blank
        showSearchSuggestions: true
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  docker.yaml: ""
