apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.containo.us
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
      - apiextensions.k8s.io
    resources:
      - nodes
      - pods
      - customresourcedefinitions/status
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations: {}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: homepage-config
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingress
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/description: Dynamically Detected Homepage
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Cluster Management
    gethomepage.dev/icon: homepage.png
    gethomepage.dev/name: Homepage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homepage.local.timmybtech.com`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    avp.kubernetes.io/path: "secret/data/homepage"
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Bryant Homelab
    headerStyle: boxed
    layout:
      Kubernetes:
        icon: mdi-sail-boat
        style: row
        columns: 2
      Kubernetes hidden:
        header: false
        style: row
        columns: 3
      OCI:
        icon: mdi-server
        style: row
        columns: 3
      OCI hidden:
        header: false
        style: row
        columns: 3
      Proxmox:
        icon: mdi-server
        style: row
        columns: 2
      Storage:
        icon: mdi-database-check
        style: row
        columns: 1
      VM/LXC:
        icon: mdi-server
        style: row
        columns: 3
      VM/LXC hidden:
        header: false
        style: row
        columns: 3
  bookmarks.yaml: |
    - CICD:
        - Netlify:
            - abbr: NL
              href: https://app.netlify.com/
        - Renovate (GitHub App):
            - abbr: RG
              href: https://developer.mend.io/
        - Terraform Cloud:
            - abbr: TC
              href: https://app.terraform.io/app/Bryant-homelab/workspaces
    - Cloud:
        - Oracle Cloud:
            - abbr: OC
              href: https://cloud.oracle.com/
    - Observability:
        - Grafana Cloud:
            - abbr: GC
              href: https://grafana.com/auth/sign-in/?plcmt=top-nav&cta=myaccount
        - Netdata Cloud:
            - abbr: NC
              href: https://app.netdata.cloud/
        - Yandex Metrica:
            - abbr: YM
              href: https://metrica.yandex.com/
    - Networking:
        - Cloudflare:
            - abbr: CF
              href: https://dash.cloudflare.com/
        - Tailscale:
            - abbr: TS
              href: https://login.tailscale.com/
        - Ngrok:
            - abbr: NG
              href: https://dashboard.ngrok.com/
    - Storage:
        - Synology Account:
            - abbr: SYA
              href: https://account.synology.com/en-us/overview?en-us=
  services.yaml: |
    - Kubernetes:
        - Grafana:
            icon: grafana.png
            href: https://grafana.timmybtech.com/
            namespace: grafana
            app: grafana
            widget:
                type: grafana
                url: https://grafana.local.timmybtech.com
                username: <GRAFANA_USER>
                password: <GRAFANA_PASSWORD>
        - Traefik-k8s:
            icon: traefik.png
            href: https://traefik.local.timmybtech.com/
            namespace: traefik
            app: traefik
            widget:
              type: traefik
              url: https://traefik.local.timmybtech.com
              username: <TRAEFIK_USER>
              password: <TRAEFIK_PASSWORD>

    - Kubernetes hidden:
        - ArgoCD:
            icon: argocd.png
            href: https://argocd.local.timmybtech.com/
            namespace: argocd
            app: argocd-server
        - Firefly-iii:
            icon: firefly.png
            href: https://firefly.local.timmybtech.com/
            namespace: firefly-iii
            app: firefly-iii
        - Firefly-iii Importer:
            icon: firefly.png
            href: https://firefly-importer.local.timmybtech.com/
            namespace: firefly-iii
            app: importer
        - Gitea:
            icon: gitea.png
            href: "https://gitea.local.timmybtech.com/"
            namespace: gitea
            app: gitea
        - Homebox:
            icon: homebox.png
            href: https://homebox.local.timmybtech.com/
            namespace: homebox
            app: homebox
        - InfluxDB:
            icon: influxdb.png
            href: https://influxdb.local.timmybtech.com/
            namespace: influxdb
            app: influxdb
        - Kube-State-Metrics:
            icon: kubernetes.png
            href: https://kube-state-metrics.local.timmybtech.com/
            namespace: kube-system
            app: kube-state-metrics
        - MinIO:
            icon: minio.png
            href: https://minio.local.timmybtech.com/
            namespace: minio
            app: minio
        - ntfy:
            icon: ntfy.png
            href: https://ntfy.local.timmybtech.com/
            namespace: ntfy
            app: ntfy
        - Planka:
            icon: planka.png
            href: https://planka.local.timmybtech.com/
            namespace: planka
            app: planka
        - Portainer (k8s):
            icon: portainer.png
            href: https://portainer.local.timmybtech.com/
            namespace: portainer
            app: portainer
        - Shlink:
            icon: shlink.png
            href: https://app.shlink.io/
            namespace: shlink
            app: shlink
        - Vault:
            icon: vault.png
            href: https://vault.local.timmybtech.com/
            namespace: vault
            app: vault
        - Whoogle:
            icon: whooglesearch.png
            href: https://whoogle.local.timmybtech.com/
            namespace: whoogle-search
            app: whoogle

    - OCI:
        - Gotify:
            icon: gotify.png
            href: https://gotify.local.timmybtech.com/
            ping: http://homelab-oci03.tbryant.headscale.com:8080
            widget:
                type: gotify
                url: http://homelab-oci03.tbryant.headscale.com:8080
                key: <GOTIFY_CLIENT_TOKEN>
        - Portainer (homelab-oci03):
            icon: portainer.png
            href: https://portainer.local.timmybtech.com/#!/13/docker/dashboard
            namespace: portainer
            app: portainer
            widget:
                type: portainer
                url: https://portainer.local.timmybtech.com
                env: 13
                key: <PORTAINER_ACCESS_TOKEN>
        - Uptime Kuma:
            icon: uptime-kuma.png
            href: https://uptime-kuma.local.timmybtech.com/
            ping: http://homelab-oci03.tbryant.headscale.com:3001
            widget:
                type: uptimekuma
                url: http:///homelab-oci03.tbryant.headscale.com:3001
                slug: bryant-homelab

    - OCI hidden:
        - Healthchecks:
            icon: healthchecks.png
            href: https://healthchecks.local.timmybtech.com/
            ping: http://homelab-oci03.tbryant.headscale.com:8000
        - PGweb (oci):
            icon: postgres.png
            href: https://pgweb-oci.local.timmybtech.com/
            ping: http://homelab-oci03.tbryant.headscale.com:8083
        - IT-Tools:
            icon: it-tools.png
            href: https://it-tools.local.timmybtech.com/
            ping: http://homelab-oci03.tbryant.headscale.com:5884

    - Storage:
        - Synology:
            icon: synology.png
            href: https://nas.local.timmybtech.com/
            ping: http://192.168.86.44:5000/
            widget:
                type: diskstation
                url: http://192.168.86.44:5000/
                username: <SYNOLOGY_USER>
                password: <SYNOLOGY_PASSWORD>

    - Proxmox:
        - Proxmox2:
            icon: proxmox.png
            href: https://pve.local.timmybtech.com/
            ping: https://192.168.86.160:8006
        - Proxmox 3:
            icon: proxmox.png
            href: https://192.168.86.199:8006
            ping: https://192.168.86.199:8006

    - VM/LXC:
        - Speedtest-tracker:
            icon: speedtest-tracker.png
            href: https://speedtest.local.timmybtech.com/
            ping: http://192.168.86.143:8083
            widget:
                type: speedtest
                url: http://192.168.86.143:8083
        - Portainer (vm303):
            icon: portainer.png
            href: https://portainer.local.timmybtech.com/#!/11/docker/dashboard
            namespace: portainer
            app: portainer
            widget:
                type: portainer
                url: https://portainer.local.timmybtech.com
                env: 11
                key: <PORTAINER_ACCESS_TOKEN>
        - Prometheus:
            icon: prometheus.png
            href: http://prometheus.tbryant.headscale.com:9090/
            ping: http://prometheus.tbryant.headscale.com:9090
            widget:
                type: prometheus
                url: http://prometheus.tbryant.headscale.com:9090

    - VM/LXC hidden:
        - SNMP Exporter:
            icon: prometheus.png
            href: http://192.168.86.174:9116/
            ping: http://192.168.86.174:9116/
        - Technitium:
            icon: technitium.png
            href: https://technitium.local.timmybtech.com/
            ping: http://192.168.86.213:5380
        - Code Server:
            icon: code-server.png
            href: https://code-server.local.timmybtech.com/
            ping: http://192.168.86.159:8680
        - Focal-Board:
            icon: focalboard.png
            href: https://focal-board.local.timmybtech.com/
            ping: http://192.168.86.143:8001
        - Home Assistant:
            icon: home-assistant.png
            href: https://homeassistant.local.timmybtech.com/
            ping: http://192.168.86.147:8123
        - LinkAce:
            icon: linkace.png
            href: https://linkace.local.timmybtech.com/
            ping: http://192.168.86.143:718
        - Loki:
            icon: loki.png
            href: https://loki.local.timmybtech.com/
            ping: http://192.168.86.146:3100/loki/api/v1/status/buildinfo
        - PGweb (vm303):
            icon: postgres.png
            href: https://pgweb.local.timmybtech.com/
            ping: http://192.168.86.74:8081
        - WatchYourLAN:
            icon: homepage.png
            href: https://watchyourlan.local.timmybtech.com/
            ping: http://192.168.86.217:8840
        - Zipline:
            icon: zipline.png
            href: https://zipline.local.timmybtech.com/
            ping: http://192.168.86.143:3000
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: false
        cpu: false
        memory: false
    # - search:
    #     provider: custom
    #     url: https://whoogle.local.timmybtech.com/
    #     target: _blank
    - weatherapi:
        latitude: 41.8978
        longitude: -70.9090
        units: imperial
        apiKey: <WEATHERAPI_API_KEY>
        cache: 15
  docker.yaml: ""
