# USE THIS ONE!
# envsubst < argocd-cm.yaml | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  statusbadge.enabled: "true"
  admin.enabled: "true"
  exec.enabled: "true"
  url: https://argocd.local.timmybtech.com

  # Local users
  accounts.readonlyuser: apiKey
  accounts.readonlyuser.enabled: "true"
  accounts.tbryant: apiKey, login
  accounts.tbryant.enabled: "true"

  dex.config: |
    connectors:
    - config:
        issuer: ${AUTHENTIK_ARGOCD_ISSUER}
        clientID: ${AUTHENTIK_ARGOCD_CLIENT_ID}
        clientSecret: $dex.authentik.clientSecret
        insecureEnableGroups: true
        scopes:
          - openid
          - profile
          - email
      name: authentik
      type: oidc
      id: authentik

  resource.customizations: |
    rbac.authorization.k8s.io/ClusterRole:
      ignoreDifferences: |
        jsonPointers:
        - /rules

  resource.customizations.ignoreResourceUpdates.all: |
    jsonPointers:
      - /status

  resource.customizations.ignoreResourceUpdates.ConfigMap: |
    jqPathExpressions:
      - '.metadata.annotations."cluster-autoscaler.kubernetes.io/last-updated"'
      - '.metadata.annotations."control-plane.alpha.kubernetes.io/leader"'

  resource.customizations.ignoreResourceUpdates.Endpoints: |
    jsonPointers:
      - /metadata
      - /subsets

  resource.customizations.ignoreResourceUpdates.apps_ReplicaSet: |
    jqPathExpressions:
      - '.metadata.annotations."deployment.kubernetes.io/desired-replicas"'
      - '.metadata.annotations."deployment.kubernetes.io/max-replicas"'
      - '.metadata.annotations."rollout.argoproj.io/desired-replicas"'

  resource.customizations.ignoreResourceUpdates.argoproj.io_Application: |
    jqPathExpressions:
      - '.metadata.annotations."notified.notifications.argoproj.io"'
      - '.metadata.annotations."argocd.argoproj.io/refresh"'
      - '.metadata.annotations."argocd.argoproj.io/hydrate"'
      - '.operation'

  resource.customizations.ignoreResourceUpdates.argoproj.io_Rollout: |
    jqPathExpressions:
      - '.metadata.annotations."notified.notifications.argoproj.io"'

  resource.customizations.ignoreResourceUpdates.autoscaling_HorizontalPodAutoscaler:
    |
    jqPathExpressions:
      - '.metadata.annotations."autoscaling.alpha.kubernetes.io/behavior"'
      - '.metadata.annotations."autoscaling.alpha.kubernetes.io/conditions"'
      - '.metadata.annotations."autoscaling.alpha.kubernetes.io/metrics"'
      - '.metadata.annotations."autoscaling.alpha.kubernetes.io/current-metrics"'

  resource.customizations.ignoreResourceUpdates.discovery.k8s.io_EndpointSlice:
    |
    jsonPointers:
      - /metadata
      - /endpoints
      - /ports

  resource.exclusions: |
    ### Network resources created by the Kubernetes control plane
    - apiGroups:
      - ''
      - discovery.k8s.io
      kinds:
      - Endpoints
      - EndpointSlice
    ### Internal Kubernetes resources
    - apiGroups:
      - coordination.k8s.io
      kinds:
      - Lease
    ### Internal Kubernetes Authz/Authn resources
    - apiGroups:
      - authentication.k8s.io
      - authorization.k8s.io
      kinds:
      - SelfSubjectReview
      - TokenReview
      - LocalSubjectAccessReview
      - SelfSubjectAccessReview
      - SelfSubjectRulesReview
      - SubjectAccessReview
    ### Intermediate Certificate Requests
    - apiGroups:
      - certificates.k8s.io
      kinds:
      - CertificateSigningRequest
    - apiGroups:
      - cert-manager.io
      kinds:
      - CertificateRequest
    ### Cilium internal resources
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      - CiliumEndpoint
      - CiliumEndpointSlice
    ### Kyverno intermediate and reporting resources
    - apiGroups:
      - kyverno.io
      - reports.kyverno.io
      - wgpolicyk8s.io
      kinds:
      - PolicyReport
      - ClusterPolicyReport
      - EphemeralReport
      - ClusterEphemeralReport
      - AdmissionReport
      - ClusterAdmissionReport
      - BackgroundScanReport
      - ClusterBackgroundScanReport
      - UpdateRequest
