apiVersion: v1
kind: Namespace
metadata:
  name: termix

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: termix-data
  namespace: termix
spec:
  storageClassName: nfs-csi-synologynas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: termix
  namespace: termix
  labels:
    app: termix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: termix
  template:
    metadata:
      labels:
        app: termix
    spec:
      containers:
        - name: termix
          image: ghcr.io/lukegus/termix:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: termix-data

---
apiVersion: v1
kind: Service
metadata:
  name: termix
  namespace: termix
  labels:
    app: termix
spec:
  selector:
    app: termix
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: termix-internal
  namespace: termix
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`termix.local.timmybtech.com`)
      kind: Rule
      services:
        - name: termix
          port: 8080
  tls:
    secretName: local-timmybtech-com-tls
