settings:
  clusterName: default

plugins:
  repositories:
    botkube:
      url: https://github.com/kubeshop/botkube/releases/download/v1.1.1/plugins-index.yaml

executors:
  "k8s-tools":
    botkube/kubectl:
      enabled: true
      config:
        defaultNamespace: "default"
        interactiveBuilder:
          allowed:
            namespaces: ["default"]
            verbs: ["api-resources", "api-versions", "cluster-info", "describe", "explain", "get", "logs", "top"]
            resources: ["deployments", "pods", "namespaces"]
      context:
        rbac:
          group:
            type: Static
            static:
              values: [botkube-plugins-default]

    botkube/helm:
      enabled: true
      config:
        helmDriver: "secret"
        helmCacheDir: "/tmp/helm/.cache"
        helmConfigDir: "/tmp/helm/"
      context:
        rbac:
          group:
            type: Static
            static:
              values: [botkube-plugins-default]

analytics:
  disable: true

sources:
  'prometheus':
    botkube/prometheus:
      enabled: true
      config:
        url: "https://prometheus.local.timmybtech.com"
        ignoreOldAlerts: true
        alertStates: ["firing", "pending", "inactive"]
        log:
          level: info

aliases:
  kk:
    command: kubectl
    displayName: "Kubectl alias"
  chatgpt:
    command: doctor
    displayName: "Doctor alias"
  kgp:
    command: kubectl get pods
    displayName: "Get pods"
