apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: botkube
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    avp.kubernetes.io/path: "secret/data/botkube"
spec:
  destination:
    namespace: botkube
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://charts.botkube.io
    targetRevision: 1.1.1
    chart: botkube
    helm:
      releaseName: botkube
      parameters:
      - name: "communications.default-group.discord.enabled"
        value: "true"
      - name: "communications.default-group.discord.botID"
        value: "<DISCORD_BOT_ID>"
      - name: "communications.default-group.discord.token"
        value: "<DISCORD_TOKEN>"
      - name: "communications.default-group.discord.channels.default.id"
        value: "<DISCORD_CHANNEL_ID>"
      - name: "executors.ai.botkube/doctor.enabled"
        value: "true"
      - name: "executors.ai.botkube/doctor.config.apiKey"
        value: "<OPENAI_API_KEY>"
      values: |
        settings:
          clusterName: default

        plugins:
          repositories:
            botkube:
              url: https://github.com/kubeshop/botkube/releases/download/v1.1.1/plugins-index.yaml

        executors:
          "k8s-tools":
            botkube/kubectl:
              enabled: true
              config:
                defaultNamespace: "default"
                interactiveBuilder:
                  allowed:
                    namespaces: ["default"]
                    verbs: ["api-resources", "api-versions", "cluster-info", "describe", "explain", "get", "logs", "top"]
                    resources: ["deployments", "pods", "namespaces"]
              context:
                rbac:
                  group:
                    type: Static
                    static:
                      values: [botkube-plugins-default]

            botkube/helm:
              enabled: true
              config:
                helmDriver: "secret"
                helmCacheDir: "/tmp/helm/.cache"
                helmConfigDir: "/tmp/helm/"
              context:
                rbac:
                  group:
                    type: Static
                    static:
                      values: [botkube-plugins-default]

        analytics:
          disable: true

        sources:
          'prometheus':
            botkube/prometheus:
              enabled: true
              config:
                url: "https://prometheus.local.timmybtech.com"
                ignoreOldAlerts: true
                alertStates: ["firing", "pending", "inactive"]
                log:
                  level: info

        aliases:
          kk:
            command: kubectl
            displayName: "Kubectl alias"
          chatgpt:
            command: doctor
            displayName: "Doctor alias"
          kgp:
            command: kubectl get pods
            displayName: "Get pods"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
