---
apiVersion: v1
kind: Namespace
metadata:
  name: urlchecker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checks
  namespace: urlchecker
data:
  checks.yaml: |
    - name: actualbudget
      url: https://budget.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: argocd
      url: https://argocd.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: adguard
      url: https://adguard.local.timmybtech.com
      retries: 2
      status_accepted:
        - 200

    - name: gitea
      url: https://gitea.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: dozzle
      url: https://dozzle.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: glance
      url: https://glance.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: healthchecks
      url: https://healthchecks.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: homeassistant
      url: https://homeassistant.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: influxdb
      url: https://influxdb.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: it-tools
      url: https://it-tools.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: linkace
      url: https://linkace.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: loki
      url: https://loki.local.timmybtech.com/loki/api/v1/status/buildinfo
      retries: 3
      status_accepted:
        - 200

    - name: nas
      url: https://nas.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: planka
      url: https://planka.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: portainer
      url: https://portainer.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: prometheus
      url: http://prometheus.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: silverbullet
      url: https://silverbullet.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: speedtest-tracker
      url: https://speedtest.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: uptime-kuma
      url: https://uptime-kuma.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: vault
      url: https://vault.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: watchyourlan
      url: https://watchyourlan.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: whoogle
      url: https://whoogle.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: zipline
      url: https://zipline.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlchecker
  namespace: urlchecker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlchecker
  template:
    metadata:
      labels:
        app: urlchecker
    spec:
      dnsPolicy: "None" # Use "None" to ensure custom DNS settings are applied
      dnsConfig:
        nameservers:
          - 192.168.86.214
      containers:
        - name: urlchecker
          image: timmyb824/python-urlchecker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: HEALTHCHECKS_URL_PYTHON_URLCHECKER
              value: <path:secret/data/urlchecker#HEALTHCHECKS_URL>
            # - name: APPRISE_GOTIFY
            #   value: <path:secret/data/urlchecker#APPRISE_GOTIFY>
            - name: APPRISE_DISCORD
              value: <path:secret/data/urlchecker#APPRISE_DISCORD>
            - name: APPRISE_NTFY
              value: <path:secret/data/urlchecker#APPRISE_NTFY>
            - name: TIME_BETWEEN_SCHEDULED_CHECKS
              value: "120"
          volumeMounts:
            - name: checks
              mountPath: /app/checks.yaml
              subPath: checks.yaml
      volumes:
        - name: checks
          configMap:
            name: checks
---
apiVersion: v1
kind: Service
metadata:
  name: urlchecker
  namespace: urlchecker
spec:
  selector:
    app: urlchecker
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: urlchecker-ingress
  namespace: urlchecker
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`urlchecker.local.timmybtech.com`)
      kind: Rule
      services:
        - name: urlchecker
          port: 8000
  tls:
    secretName: local-timmybtech-com-tls
