---
apiVersion: v1
kind: Namespace
metadata:
  name: urlchecker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checks
  namespace: urlchecker
data:
  checks.yaml: |
    - name: actualbudget
      url: https://budget.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: argocd
      url: https://argocd.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: code-server
      url: https://code-server.local.timmybtech.com
      retries: 2
      status_accepted:
        - 200

    - name: firefly-iii
      url: https://firefly.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: focal-board
      url: https://focal-board.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: gitea
      url: https://gitea.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: gotify
      url: https://gotify.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: grafana
      url: https://grafana.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: healthchecks
      url: https://healthchecks.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: homeassistant
      url: https://homeassistant.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: influxdb
      url: https://influxdb.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: it-tools
      url: https://it-tools.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: linkace
      url: https://linkace.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: loki
      url: https://loki.local.timmybtech.com/loki/api/v1/status/buildinfo
      retries: 3
      status_accepted:
        - 200

    - name: nas
      url: https://nas.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: planka
      url: https://planka.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: portainer
      url: https://portainer.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: prometheus
      url: http://prometheus.tbryant.headscale.com:9090
      retries: 3
      status_accepted:
        - 200

    - name: shlink
      url: https://shlink.local.timmybtech.com
      retries: 3
      status_accepted:
        - 404

    - name: speedtest-tracker
      url: https://speedtest.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: uptime-kuma
      url: https://uptime-kuma.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: vault
      url: https://vault.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: watchyourlan
      url: https://watchyourlan.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: whoogle
      url: https://whoogle.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200

    - name: zipline
      url: https://zipline.local.timmybtech.com
      retries: 3
      status_accepted:
        - 200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlchecker
  namespace: urlchecker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlchecker
  template:
    metadata:
      labels:
        app: urlchecker
    spec:
      containers:
        - name: urlchecker
          image: timmyb824/python-urlchecker:latest
          imagePullPolicy: Always
          env:
            - name: HEALTHCHECKS_URL_PYTHON_URLCHECKER
              value: <path:secret/data/urlchecker#HEALTHCHECKS_URL>
            - name: APPRISE_GOTIFY
              value: <path:secret/data/urlchecker#APPRISE_GOTIFY>
            - name: APPRISE_DISCORD
              value: <path:secret/data/urlchecker#APPRISE_DISCORD>
            - name: TIME_BETWEEN_SCHEDULED_CHECKS
              value: "120"
          volumeMounts:
            - name: checks
              mountPath: /app/checks.yaml
              subPath: checks.yaml
      volumes:
        - name: checks
          configMap:
            name: checks
