---
apiVersion: v1
kind: Namespace
metadata:
  name: mortgageratescraper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mortgageratescraper
  namespace: mortgageratescraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mortgageratescraper
  template:
    metadata:
      labels:
        app: mortgageratescraper
    spec:
      containers:
        - name: mortgageratescraper
          image: timmyb824/python-mortgageratescraper:latest
          imagePullPolicy: Always
          env:
            - name: HEALTHCHECK_URL
              value: <path:secret/data/scripts#HEALTHCHECK_URL_MORTGAGERATESCAPER>
            - name: APPRISE_NTFY
              value: <path:secret/data/mortgageratescraper#APPRISE_NTFY>
