---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: timmybtech-com
  namespace: traefik
spec:
  secretName: timmybtech-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.timmybtech.com"
  dnsNames:
  - "timmybtech.com"
  - "*.timmybtech.com"
