apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-resource-requests-limits
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: set-default-resources
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                # - Job # spec.containers not valid for this type
                # - CronJob # spec.containers not valid for this type
      mutate:
        targets:
          - apiVersion: v1
            kind: Pod
        foreach:
          - list: "spec.template.spec.containers"
            patchStrategicMerge:
              spec:
                template:
                  spec:
                    containers:
                      - (name): "{{element.name}}"
                        resources:
                          requests:
                            cpu: "100m"
                            memory: "128Mi"
                          limits:
                            cpu: "500m"
                            memory: "256Mi"
            preconditions:
              all:
                - key: "{{element.resources.requests.cpu}}"
                  operator: Equals
                  value: null
                - key: "{{element.resources.requests.memory}}"
                  operator: Equals
                  value: null
                - key: "{{element.resources.limits.cpu}}"
                  operator: Equals
                  value: null
                - key: "{{element.resources.limits.memory}}"
                  operator: Equals
                  value: null
