---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraperr
  namespace: scraperr
spec:
  template:
    spec:
      containers:
        - name: scraperr
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraperr-api
  namespace: scraperr
spec:
  template:
    spec:
      containers:
        - name: scraperr-api
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
