---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docmost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docmost
  template:
    metadata:
      labels:
        app: docmost
        app.kubernetes.io/name: docmost
    spec:
      containers:
        - name: docmost
          image: docmost/docmost:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_URL
              value: "http://localhost:3000"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: docmost-secrets
                  key: app-secret
            - name: DATABASE_URL
              value: <path:secret/data/database#PG_CONN_STRING>/docmost?schema=public
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: MAIL_DRIVER
              value: "smtp"
            - name: SMTP_HOST
              value: <path:secret/data/google_smtp#SMTP_HOST>
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USERNAME
              value: <path:secret/data/google_smtp#SMTP_USER>
            - name: SMTP_PASSWORD
              value: <path:secret/data/google_smtp#SMTP_PASSWORD>
            - name: SMTP_SECURE
              value: "false"
            - name: MAIL_FROM_ADDRESS
              value: "homelab@timmybtech.com"
            - name: MAIL_FROM_NAME
              value: "Docmost"
            - name: STORAGE_DRIVER
              value: "s3"
            - name: AWS_S3_ACCESS_KEY_ID
              value: <path:secret/data/argocd#MINIO_ACCESS_KEY>
            - name: AWS_S3_SECRET_ACCESS_KEY
              value: <path:secret/data/argocd#MINIO_SECRET_KEY>
            - name: AWS_S3_REGION
              value: "us-east-1"
            - name: AWS_S3_BUCKET
              value: "docmost"
            - name: AWS_S3_ENDPOINT
              value: "https://minio.local.timmybtech.com"
            - name: AWS_S3_FORCE_PATH_STYLE
              value: "true"

          volumeMounts:
            - name: docmost-storage
              mountPath: /app/data/storage
      volumes:
        - name: docmost-storage
          persistentVolumeClaim:
            claimName: docmost-storage
---
apiVersion: v1
kind: Secret
metadata:
  name: docmost-secrets
stringData:
  app-secret: <path:secret/data/argocd#DOCMOST_APP_SECRET>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: docmost
spec:
  selector:
    app: docmost
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: docmost-ingress
  namespace: docmost
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`docmost.local.timmybtech.com`)
      kind: Rule
      services:
        - name: docmost
          port: 3000
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: v1
kind: Secret
metadata:
  namespace: docmost
  name: tunnel-credentials
type: Opaque
stringData:
  credentials.json: >-
    <path:secret/data/cloudflared#DOCMOST_CREDENTIALS>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: docmost
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2025.4.0
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: tunnel-credentials
        - name: config
          configMap:
            name: cloudflared
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: docmost
data:
  config.yaml: |
    tunnel: docmost
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: docmost.timmybtech.com
      service: http://docmost.docmost.svc.cluster.local:3000
    - service: http_status:404
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: docmost
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    app: cloudflared
  ports:
    - port: 2000
      protocol: TCP
      targetPort: 2000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cloudflared-ingress-docmost
  namespace: docmost
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cf-docmost.local.timmybtech.com`)
      kind: Rule
      services:
        - name: cloudflared
          port: 2000
  tls:
    secretName: local-timmybtech-com-tls
