apiVersion: v1
kind: ConfigMap
metadata:
  name: patch-sc-script
  namespace: tools
data:
  patch-storageclass.sh: |
    #!/bin/sh
    while true; do
      kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
      sleep 10
    done
