apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageclass-patcher-role
rules:
- apiGroups: [""]
  resources: ["nodes", "persistentvolumes", "persistentvolumeclaims", "namespaces"]
  verbs: ["list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "patch", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storageclass-patcher-sa
  namespace: tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storageclass-patcher-rolebinding
subjects:
- kind: ServiceAccount
  name: storageclass-patcher-sa
  namespace: tools
roleRef:
  kind: ClusterRole
  name: storageclass-patcher-role
  apiGroup: rbac.authorization.k8s.io
