apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjob-patch-sc
  namespace: tools
  labels:
    app: cronjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronjob
  template:
    metadata:
      labels:
        app: cronjob
    spec:
      serviceAccountName: storageclass-patcher-sa
      containers:
      - name: cronjob
        # this image includes but /bin/sh and kubectl
        image: portainer/kubectl-shell:latest
        args:
        - /bin/sh
        - -c
        - sh /config/patch-storageclass.sh
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /config
          name: patch-script-config
      volumes:
      - name: patch-script-config
        configMap:
          name: patch-sc-script
