---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: prometheus-server
  name: prometheus-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi-synologynas
  resources:
    requests:
      storage: "32Gi"

