---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-backup-tool
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-backup-tool
  namespace: grafana-backup-tool
  annotations:
    avp.kubernetes.io/path: "secret/data/grafanaBackupTool"
data:
  GRAFANA_URL: <GRAFANA_URL>
  GRAFANA_TOKEN: <GRAFANA_TOKEN>
  GRAFANA_ADMIN_ACCOUNT: <GRAFANA_ADMIN_ACCOUNT>
  GRAFANA_ADMIN_PASSWORD: <GRAFANA_ADMIN_PASSWORD>
  AWS_ENDPOINT_URL: <AWS_ENDPOINT_URL>
  AWS_S3_BUCKET_NAME: <AWS_S3_BUCKET_NAME>
  AWS_S3_BUCKET_KEY: "daily"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
---
# Run grafana-backup-tool daily and store backups in an S3
# compatible object storage such as minio
apiVersion: batch/v1
kind: CronJob
metadata:
  name: grafana-backup-tool
  namespace: grafana-backup-tool
  labels:
    app: grafana-backup-tool
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    metadata:
      labels:
        app: grafana-backup-tool
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: grafana-backup-tool
              # The original owners of this image are ysde/docker-grafana-backup-tool
              # but there was a bug the owners never fixed. This is a fork of the original image with the bug fixed.
              # https://hub.docker.com/r/dealfa/grafana-backup-tool
              # Update 2025-08-18: Updated to use the forked image from my local registry.
              image: "registry.local.timmybtech.com/grafana-backup-tool-fork:latest"
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: grafana-backup-tool
