---
apiVersion: v1
kind: Namespace
metadata:
  name: manyfold
---
apiVersion: v1
kind: Secret
metadata:
  name: manyfold-secret
  namespace: manyfold
  annotations:
    avp.kubernetes.io/path: "secret/data/database"
type: Opaque
stringData:
  SECRET_KEY_BASE: <path:secret/data/argocd#MANYFOLD_SECRET_KEY_BASE>
  DATABASE_HOST: <path:secret/data/database#PG_HOST>
  DATABASE_NAME: "manyfold"
  DATABASE_USER: <path:secret/data/database#PG_USER>
  DATABASE_PASSWORD: <path:secret/data/database#PG_PASSWORD>
  REDIS_URL: <path:secret/data/database#REDIS_CONN_STRING>/3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manyfold-libraries-pvc
  namespace: manyfold
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-csi-synologynas
  resources:
    requests:
      storage: 24Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manyfold
  namespace: manyfold
  labels:
    app: manyfold
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manyfold
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: manyfold
        app.kubernetes.io/name: manyfold
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 1000
      containers:
        - name: manyfold
          image: ghcr.io/manyfold3d/manyfold:0.147.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3214
              protocol: TCP
          env:
            - name: DATABASE_ADAPTER
              value: postgresql
            - name: DATABASE_PORT
              value: "5432"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          envFrom:
            - secretRef:
                name: manyfold-secret
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: libraries
              mountPath: /libraries
      volumes:
        - name: libraries
          persistentVolumeClaim:
            claimName: manyfold-libraries-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: manyfold
  namespace: manyfold
  labels:
    app: manyfold
spec:
  selector:
    app: manyfold
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3214
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: manyfold-internal
  namespace: manyfold
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`manyfold.local.timmybtech.com`)
      kind: Rule
      services:
        - name: manyfold
          port: 80
  tls:
    secretName: local-timmybtech-com-tls
