---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-timmybtech-com-staging
  namespace: traefik
spec:
  secretName: dev-timmybtech-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.dev.timmybtech.com"
  dnsNames:
    - "dev.timmybtech.com"
    - "*.dev.timmybtech.com"
