# kubectl patch deployment argocd-repo-server -n argocd --patch-file patches/sops-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /age/key.txt
          volumeMounts:
            - mountPath: /age
              name: age
              readOnly: true
      volumes:
        - name: age
          secret:
            secretName: age-key
            items:
              - key: key.txt
                path: key.txt
