## OLD VERSION
# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-staging
# spec:
#   acme:
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     email: ${EMAIL}
#     privateKeySecretRef:
#       name: letsencrypt-staging
#     solvers:
#       - dns01:
#           cloudflare:
#             email: ${EMAIL}
#             apiTokenSecretRef:
#               name: cloudflare-token
#               key: cloudflare-token
#         selector:
#           dnsZones:
#             - "timmybtech.com"
## END OLD VERSION
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${EMAIL}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-token
              key: cloudflare-token
        selector:
          dnsZones:
            - "timmybtech.com"
