apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: loki
  creationTimestamp: null
  name: loki-pvc
spec:
  storageClassName: nfs-csi-synologynas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
