apiVersion: v1
kind: Secret
metadata:
  name: mattermost-postgres-connection
  namespace: mattermost
type: Opaque
stringData:
  DB_CONNECTION_STRING: <path:secret/data/database#PG_CONN_STRING>/mattermost?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: mattermost-s3-credentials
  namespace: mattermost
type: Opaque
stringData:
  accesskey: <path:secret/data/argocd#MINIO_ACCESS_KEY>
  secretkey: <path:secret/data/argocd#MINIO_SECRET_KEY>
---
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
  namespace: mattermost
spec:
  size: 100users
  ingress:
    enabled: false
    host: mattermost.timmybtech.com
    annotations:
      kubernetes.io/ingress.class: traefik-external
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
  database:
    external:
      secret: mattermost-postgres-connection
  fileStore:
    external:
      url: minio.local.timmybtech.com
      bucket: mattermost
      secret: mattermost-s3-credentials
  version: 10.7.1
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mattermost-internal
  namespace: mattermost
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mattermost.local.timmybtech.com`)
      kind: Rule
      services:
        - name: mattermost
          port: 8065
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mattermost-public
  namespace: mattermost
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mattermost.timmybtech.com`)
      kind: Rule
      services:
        - name: mattermost
          port: 8065
  tls:
    secretName: timmybtech-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mattermost-metrics-ingress
  namespace: mattermost
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mattermost-metrics.local.timmybtech.com`)
      kind: Rule
      services:
        - name: mattermost
          port: 8067
  tls:
    secretName: local-timmybtech-com-tls
