apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-auth
  namespace: authentik
type: Opaque
stringData:
  DB_USER: "<path:secret/data/authentik#PG_USER>" 
  DB_PASSWORD: "<path:secret/data/authentik#PG_PASSWORD>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: authentik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:v1.25.2-p0
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: pgbouncer-auth
          env:
            - name: DB_HOST
              value: "postgresql.homelab.lan"
            - name: DB_NAME
              value: "authentik_utf8"
            - name: POOL_MODE
              value: "transaction"
            - name: MAX_CLIENT_CONN
              value: "200"
            - name: DEFAULT_POOL_SIZE
              value: "20"
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: authentik
spec:
  selector:
    app: pgbouncer
  ports:
    - port: 5432
      targetPort: 5432
