---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-internal
  namespace: authentik
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`authentik.local.timmybtech.com`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
      # middlewares:
      #   - name: crowdsec-bouncer
      #     namespace: traefik
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-public
  namespace: authentik
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`authentik.timmybtech.com`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
    - match: "Host(`authentik.timmybtech.com`) && PathPrefix(`/outpost.goauthentik.io/`)"
      kind: Rule
      priority: 15
      services:
        - name: ak-outpost-authentik-embedded-outpost
          port: 9000
  tls:
    secretName: timmybtech-com-tls
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-metrics
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/name: authentik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-metrics-ingress
  namespace: authentik
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`authentik-metrics.local.timmybtech.com`)
      kind: Rule
      services:
        - name: authentik-metrics
          port: 9300
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik
  namespace: authentik
  annotations: {}
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: authentik-server
      port:
        number: 80
  tls:
    - hosts:
        - authentik
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: authentik
