apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: authentik
stringData:
  secret-key: <path:secret/data/authentik#SECRET_KEY>
  pg-host: <path:secret/data/authentik#PG_HOST>
  pg-user: <path:secret/data/authentik#PG_USER>
  pg-password: <path:secret/data/authentik#PG_PASSWORD>
  smtp-user: <path:secret/data/authentik#SMTP_USER>
  smtp-password: <path:secret/data/authentik#SMTP_PASSWORD>
