apiVersion: v1
kind: Secret
metadata:
  name: authentik
  namespace: authentik
stringData:
  AUTHENTIK_SECRET_KEY: <path:secret/data/authentik#SECRET_KEY>
  AUTHENTIK_POSTGRESQL__HOST: <path:secret/data/authentik#PG_HOST>
  AUTHENTIK_POSTGRESQL__NAME: "authentik"
  AUTHENTIK_POSTGRESQL__USER: <path:secret/data/authentik#PG_USER>
  AUTHENTIK_POSTGRESQL__PASSWORD: <path:secret/data/authentik#PG_PASSWORD>
  AUTHENTIK_POSTGRESQL__PORT: "5432"
  AUTHENTIK_EMAIL__HOST: "smtp.gmail.com"
  AUTHENTIK_EMAIL__PORT: "587"
  AUTHENTIK_EMAIL__USERNAME: <path:secret/data/authentik#SMTP_USER>
  AUTHENTIK_EMAIL__PASSWORD: <path:secret/data/authentik#SMTP_PASSWORD>
  AUTHENTIK_EMAIL__USE_TLS: "false"
  AUTHENTIK_EMAIL__USE_SSL: "false"
  AUTHENTIK_EMAIL__TIMEOUT: "30"
  AUTHENTIK_EMAIL__FROM: "authentik@local.timmybtech.com"
  AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
  AUTHENTIK_ERROR_REPORTING__ENVIRONMENT: "k8s"
  AUTHENTIK_ERROR_REPORTING__SEND_PII: "false"
  AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__ASN: "/geoip/GeoLite2-ASN.mmdb"
  AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__GEOIP: "/geoip/GeoLite2-City.mmdb"
  AUTHENTIK_LOG_LEVEL: "info"
  AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE: "ghcr.io/goauthentik/%(type)s:%(version)s"
  AUTHENTIK_REDIS__HOST: "authentik-redis-master"
