apiVersion: v1
kind: Secret
metadata:
  name: authentik
  namespace: authentik
stringData:
  AUTHENTIK_SECRET_KEY: <path:secret/data/authentik#SECRET_KEY>
  AUTHENTIK_POSTGRESQL__HOST: <path:secret/data/authentik#PG_HOST>
  AUTHENTIK_POSTGRESQL__NAME: "authentik"
  AUTHENTIK_POSTGRESQL__USER: <path:secret/data/authentik#PG_USER>
  AUTHENTIK_POSTGRESQL__PASSWORD: <path:secret/data/authentik#PG_PASSWORD>
  AUTHENTIK_POSTGRESQL__PORT: "5432"
  AUTHENTIK_EMAIL__HOST: "smtp.gmail.com"
  AUTHENTIK_EMAIL__PORT: "587"
  AUTHENTIK_EMAIL__USERNAME: <path:secret/data/authentik#SMTP_USER>
  AUTHENTIK_EMAIL__PASSWORD: <path:secret/data/authentik#SMTP_PASSWORD>
  AUTHENTIK_EMAIL__USE_TLS: "false"
  AUTHENTIK_EMAIL__USE_SSL: "false"
  AUTHENTIK_EMAIL__TIMEOUT: "30"
  AUTHENTIK_EMAIL__FROM: "authentik@local.timmybtech.com"
