apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
stringData:
  AUTHENTIK_SECRET_KEY: <path:secret/data/authentik#SECRET_KEY>
  AUTHENTIK_POSTGRESQL__HOST: <path:secret/data/authentik#PG_HOST>
  AUTHENTIK_POSTGRESQL__USER: <path:secret/data/authentik#PG_USER>
  AUTHENTIK_POSTGRESQL__PASSWORD: <path:secret/data/authentik#PG_PASSWORD>
  AUTHENTIK_EMAIL__USERNAME: <path:secret/data/authentik#SMTP_USER>
  AUTHENTIK_EMAIL__PASSWORD: <path:secret/data/authentik#SMTP_PASSWORD>
