autoscaler:
  image:
    repository: ghcr.io/keyval-dev/odigos/autoscaler
    tag: v0.1.69

scheduler:
  image:
    repository: ghcr.io/keyval-dev/odigos/scheduler
    tag: v0.1.72

langDetector:
  image:
    repository: ghcr.io/keyval-dev/odigos/lang-detector
    tag: v0.1.48

ui:
  image:
    repository: ghcr.io/keyval-dev/odigos/ui
    tag: v0.1.66

instrumentor:
  deleteLangDetectionPods: true
  image:
    repository: ghcr.io/keyval-dev/odigos/instrumentor
    tag: v0.1.72

odiglet:
  image:
    repository: ghcr.io/keyval-dev/odigos/odiglet
    tag: v0.1.72
