---
# create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: olivetin
---
apiVersion: v1
kind: Secret
metadata:
  name: olivetin-ssh-key
  namespace: olivetin
type: Opaque
data:
  id_master_key_nopass: <path:secret/data/olivetin#ID_MASTER_KEY_NOPASS_PRIVATE>
  id_master_key_nopass.pub: <path:secret/data/olivetin#ID_MASTER_KEY_NOPASS_PUBLIC>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: olivetin-config
data:
  config.yaml: |
    logLevel: INFO

    prometheus:
        enabled: true
        defaultGoMetrics: false

    actions:
      - title: ping the internet
        shell: ping 1.1.1.1 -c 1
        icon: ping
        timeout: 3

      - title: whoami on hp-laptop-ubuntu
        shell: ssh -i /home/olivetin/.ssh/id_master_key_nopass tbryant@192.168.86.53 'whoami'
        icon: ping
        timeout: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivetin
  namespace: olivetin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olivetin
  template:
    metadata:
      labels:
        app: olivetin
        app.kubernetes.io/name: olivetin
    spec:
      containers:
        - name: olivetin
          image: docker.io/jamesread/olivetin:2024.09.11
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Debug: List contents of /ssh-keys
              echo "Contents of /ssh-keys:"
              ls -la /ssh-keys

              # Create .ssh directory
              mkdir -p /home/olivetin/.ssh

              # Copy SSH keys
              cp /ssh-keys/* /home/olivetin/.ssh/ || echo "Failed to copy SSH keys"

              # Set permissions
              chown -R olivetin:olivetin /home/olivetin/.ssh
              chmod 700 /home/olivetin/.ssh
              chmod 600 /home/olivetin/.ssh/*

              # Move and set permissions for the private key
              mv /home/olivetin/.ssh/id_master_key_nopass /home/olivetin/id_master_key_nopass
              chown olivetin:olivetin /home/olivetin/id_master_key_nopass
              chmod 600 /home/olivetin/id_master_key_nopass

              # Debug: List contents of /home/olivetin
              echo "Contents of /home/olivetin:"
              ls -la /home/olivetin
              echo "Contents of /home/olivetin/.ssh:"
              ls -la /home/olivetin/.ssh

              # Start OliveTin as olivetin user
              exec su -c "/usr/local/bin/olivetin" olivetin
          ports:
            - containerPort: 1337
          volumeMounts:
            - name: olivetin-config
              mountPath: "/config"
              readOnly: true
            - name: ssh-keys
              mountPath: "/ssh-keys"
              readOnly: true
          livenessProbe:
            exec:
              command:
                - curl
                - localhost:1337
            initialDelaySeconds: 5
            periodSeconds: 30
      volumes:
        - name: olivetin-config
          configMap:
            name: olivetin-config
        - name: ssh-keys
          secret:
            secretName: olivetin-ssh-key
            defaultMode: 0400
---
apiVersion: v1
kind: Service
metadata:
  name: olivetin
  namespace: olivetin
spec:
  selector:
    app: olivetin
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: olivetin-ingress
  namespace: olivetin
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`olivetin.local.timmybtech.com`)
      kind: Rule
      services:
        - name: olivetin
          port: 1337
  tls:
    secretName: local-timmybtech-com-tls
