---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-repo-server-vault-plugin-credentials-reader
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
    resourceNames: ["argocd-vault-plugin-credentials"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-repo-server-vault-plugin-credentials-reader
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-repo-server
    namespace: argocd
roleRef:
  kind: Role
  name: argocd-repo-server-vault-plugin-credentials-reader
  apiGroup: rbac.authorization.k8s.io
