---
# envsubst < argocd-vault-plugin-credentials.yaml | kubectl apply -f -
kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
# can change back to `data` (vs stringData) by encoding the values with base64 (e.g. `htpasswd -nb AVP_ROLE_ID | openssl base64` or `echo -n "AVP_ROLE_ID" | base64`)
stringData:
  AVP_AUTH_TYPE: approle
  AVP_ROLE_ID: ${AVP_ROLE_ID}
  AVP_SECRET_ID: ${AVP_SECRET_ID}
  AVP_TYPE: vault
  VAULT_ADDR: "https://vault.local.timmybtech.com"