apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  storageClassName: nfs-csi-synologynas
  volumeName: pvc-98c7f0e2-c1fd-482c-ba30-6e46ce79c880
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-internal
  namespace: immich
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich.local.timmybtech.com`)
      kind: Rule
      services:
        - name: immich-server
          port: 2283
      # middlewares:
      #   - name: crowdsec-bouncer
      #     namespace: traefik
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-public
  namespace: immich
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich.timmybtech.com`)
      kind: Rule
      services:
        - name: immich-server
          port: 2283
  tls:
    secretName: timmybtech-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-api-metrics-ingress
  namespace: immich
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich-api-metrics.local.timmybtech.com`)
      kind: Rule
      services:
        - name: immich-server
          port: 8081
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-microservices-metrics-ingress
  namespace: immich
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich-microservices-metrics.local.timmybtech.com`)
      kind: Rule
      services:
        - name: immich-server
          port: 8082
  tls:
    secretName: local-timmybtech-com-tls
