---
apiVersion: v1
kind: Namespace
metadata:
  name: glance
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: calendar

              - type: rss
                limit: 10
                collapse-after: 3
                cache: 3h
                feeds:
                  - url: https://ciechanow.ski/atom.xml
                  - url: https://www.joshwcomeau.com/rss.xml
                    title: Josh Comeau
                  - url: https://samwho.dev/rss.xml
                  - url: https://awesomekling.github.io/feed.xml
                  - url: https://ishadeed.com/feed.xml
                    title: Ahmad Shadeed

              - type: twitch-channels
                channels:
                  - theprimeagen
                  - cohhcarnage
                  - christitustech
                  - blurbs
                  - asmongold
                  - jembawls

          - size: full
            widgets:
              - type: hacker-news

              - type: videos
                channels:
                  - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                  - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
                  - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim

              - type: reddit
                subreddit: selfhosted

          - size: small
            widgets:
              - type: weather
                location: Middleborough, Massachusetts, United States

              - type: dns-stats
                service: adguard
                url: https://adguard.local.timmybtech.com/
                username: <path:secret/data/homepage#ADGUARD_USER>
                password: <path:secret/data/homepage#ADGUARD_PASSWORD>

              - type: markets
                markets:
                  - symbol: SPY
                    name: SPDR S&P 500
                  - symbol: SOXX
                    name: iShares PHLX Semiconductor ETF
                  - symbol: VOO
                    name: Vanguard S&P 500 ETF
                  - symbol: QQQ
                    name: Invesco QQQ ETF
                  - symbol: AMZN
                    name: Amazon
                  - symbol: TSM
                    name: Taiwan Semiconductor Manufacturing Company Ltd.
                  - symbol: SFY
                    name: SoFi Select 500 ETF
                  - symbol: SOFI
                    name: SoFi Bank
                  - symbol: FDEEX
                    name: Fidelity Freedom 2055 Fund
                  - symbol: FFRHX
                    name: Fidelity Floating Rate High Income Fund
                  - symbol: FPURX
                    name: Fidelity Puritan Fund
                  - symbol: PRRJX
                    name: Putnam Sustainable Retirement 2050 Fund
                  - symbol: VIG
                    name: Vanguard Dividend Appreciation ETF

      - name: Gaming
        columns:
          - size: small
            widgets:
              - type: twitch-top-games
                limit: 20
                collapse-after: 13
                exclude:
                  - just-chatting
                  - pools-hot-tubs-and-beaches
                  - music
                  - art
                  - asmr

          - size: full
            widgets:
              - type: group
                widgets:
                  - type: reddit
                    show-thumbnails: true
                    subreddit: pcgaming
                  - type: reddit
                    subreddit: games

              - type: videos
                style: grid-cards
                collapse-after-rows: 3
                channels:
                  - UCNvzD7Z-g64bPXxGzaQaa4g # gameranx
                  - UCZ7AeeVbyslLM_8-nVy2B8Q # Skill Up
                  - UCHDxYLv8iovIbhrfl16CNyg # GameLinked
                  - UC9PBzalIcEQCsiIkq36PyUA # Digital Foundry

          - size: small
            widgets:
              - type: reddit
                subreddit: gamingnews
                limit: 7
                style: vertical-cards
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glance
  template:
    metadata:
      labels:
        app: glance
        app.kubernetes.io/name: glance
    spec:
      containers:
        - name: glance
          image: glanceapp/glance:v0.7.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /app/config/glance.yml
              subPath: glance.yml
            - name: timezone
              mountPath: /etc/timezone
              readOnly: true
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: glance-config
        - name: timezone
          hostPath:
            path: /etc/timezone
            type: File
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: glance-service
spec:
  selector:
    app: glance
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: glance-ingress
  namespace: glance
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`glance.local.timmybtech.com`)
      kind: Rule
      services:
        - name: glance-service
          port: 8080
  tls:
    secretName: local-timmybtech-com-tls
