---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-timmybtech-com
  namespace: default # This is the namespace where the ingress and service are to be located
spec:
  secretName: local-timmybtech-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.timmybtech.com"
  dnsNames:
  - "local.timmybtech.com"
  - "*.local.timmybtech.com"
