apiVersion: v1
kind: ServiceAccount
metadata:
  name: home-assistant
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: home-assistant-health-check
rules:
  - apiGroups: [""]
    resources: ["nodes", "componentstatuses"]
    verbs: ["get", "list"]
  - nonResourceURLs: ["/healthz"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: home-assistant-health-check-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: home-assistant-health-check
subjects:
  - kind: ServiceAccount
    name: home-assistant
    namespace: kube-system
