apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    avp.kubernetes.io/path: "secret/data/authentik"
spec:
  destination:
    namespace: authentik
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io
      targetRevision: 2025.6.3
      chart: authentik
      helm:
        releaseName: authentik
        values: |
          client:
            image: ghcr.io/bluewave-labs/checkmate-client:v3.2.0
            port: 80
            protocol: http
            ingress:
              enabled: false

          server:
            image: ghcr.io/bluewave-labs/checkmate-backend:v3.2.0
            port: 52345
            protocol: http
            ingress:
              enabled: false

          redis:
            enabled: false

          secrets:
            JWT_SECRET: change_me
          #  REFRESH_TOKEN_SECRET: change_me
          #  SYSTEM_EMAIL_ADDRESS: test@example.com
          #  SYSTEM_EMAIL_PASSWORD: change_me
          #  SYSTEM_EMAIL_HOST: smtp.example.com
          #  SYSTEM_EMAIL_PORT: "587"
          #  PAGESPEED_API_KEY: change_me
            DB_CONNECTION_STRING: mongodb://checkmate-mongodb.namespace.svc:27017/uptime_db
            CLIENT_HOST: change_me
            REDIS_HOST: <path:secret/data/database#REDIS_HOST>
          #  REDIS_PORT: "6379"
          #  DB_TYPE: MongoDB
          #  TOKEN_TTL: 99d
          #  REFRESH_TOKEN_TTL: 99d

          persistence:
            mongo:
              size: 5Gi
              storageClass: ""
            redis:
              size: 1Gi
              storageClass: ""

    - repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
      path: "gitops/manifests/authentik"
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
