apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mattermost
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://helm.mattermost.com
      targetRevision: 1.0.2
      chart: mattermost-operator
      helm:
        releaseName: mattermost
        values: |
          mattermostOperator:
            enabled: true
            replicas: 1
            rbac:
              create: true
            serviceAccount:
              create: true
            env:
              maxReconcilingInstallations: 20
              maxReconcilingConcurrency: 10
              requeuOnLimitDelay: 20s
            image:
              repository: mattermost/mattermost-operator
              tag: v1.22.0
              pullPolicy: IfNotPresent
            args:
              - --enable-leader-election
              - --metrics-addr=0.0.0.0:8383

            privateRegistry:
              enabled: false
              imagePullSecret: null

    - repoURL: "https://github.com/timmyb824/kubernetes-apps.git"
      path: "gitops/manifests/mattermost"
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSync=true
