apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: organizr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: organizr
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://k8s-at-home.com/charts
    targetRevision: 7.4.2
    chart: organizr
    helm:
      releaseName: organizr
      parameters:
      - name: "persistence.config.storageClass"
        value: "nfs-csi-synologynas"
      - name: "persistence.config.volumeName"
        value: "pvc-6087cf9b-d103-44e8-9841-eefa5fee94a8"
      - name: "persistence.config.enabled"
        value: "true"
        forceString: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: organizr-ingress
  namespace: organizr
  annotations:
    kubernetes.io/ingress.class: traefik-external
    # argocd.argoproj.io/hook: Sync
    helm.sh/hook: "post-install"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`organizr.local.timmybtech.com`) # create A record in pihole
      kind: Rule
      services:
        - name: organizr
          port: 80
  tls:
    secretName: local-timmybtech-com-tls # or local-example-com-staging-tls
